Afdas:
  adresse: 66 rue Stendhal CS 32016 75990 Paris cedex 20
  telephone: 01 44 78 39 39
  web: http://www.afdas.com
OPCO Mobilités:
  adresse: 43 bis route de Vaugirard 92190 Meudon
  telephone: 01 41 14 16 18
OPCO Construction:
  adresse: 32 rue René Boulanger CS 60033 75483 Paris cedex 10
  telephone: 01 82 83 95 00
OCAPIAT:
  adresse: 153 rue de la Pompe CS 60742 75179 Paris cedex 16
  telephone: 01 70 38 38 38
OPCO Santé:
  adresse: 31 rue Anatole France 92300 Levallois Perret
  telephone: 09 75 18 76 91
OPCO Cohésion sociale:
  adresse: 43 boulevard Diderot 75012 Paris
  telephone: 01 53 02 13 13
OPCO Entreprises de proximité:
  adresse: 53 rue Ampère 75017 Paris
ESSFIMO:
  adresse : 14 rue Riquet 75940 Paris Cedex 19
2I:
  adresse: 55 rue de Châteaudun 75009 Paris
Atlas:
  adresse: 148 boulevard Haussmann 75008 Paris
Opcommerce:
  adresse: 251 boulevard Pereire 75852 Paris Cedex 17
  telephone: 01 55 37 41 51
AGEFOS PME Antilles Guyane:
  adresse: Immeuble Arno Sons Zac de Houëlbourg Sud II 97122 Baie Mahault
  telephone: 05 90 26 93 62/05 90 41 98 16
  web: http://www.agefos-pme-antillesguyane.com
AGEFOS PME Auvergne Rhône Alpes:
  adresse: 50 rue Saint Jean de Dieu BP7077 69348 Lyon cedex 07
  telephone: 04 72 71 55 30
  web: http://www.agefos-pme-auvergnerhonealpes.com
AGEFOS PME Bourgogne Franche Comté:
  adresse: 5 rue de Broglie CS56623 21066 Dijon cedex
  telephone: 0820 420 051*
  web: http://www.agefos-pme-bfc.com
AGEFOS PME Bretagne:
  adresse: Immeuble Hermès 6 place des Colombes CS56424 35064 Rennes cedex
  telephone: 02 99 78 47 20
  web: http://www.agefos-pme-bretagne.com
AGEFOS PME Centre Val de Loire:
  adresse: 4 place Jean Monnet 45000 Orléans cedex
  telephone: 02 38 62 62 18
  web: http://www.agefos-pme-centre.com
AGEFOS PME CGM:
  adresse: 55 rue Ampère 75017 Paris
  telephone: 01 44 01 89 89
  web: agefospme-cgm.fr
AGEFOS PME Corse:
  adresse: Route du Stade Allée des Fleurs 20600 Furiani
  telephone: 04 95 58 92 00
  web: http://www.agefos-pme-corse.com
AGEFOS PME Délégation Auvergne:
  adresse: 52-54 boulevard Berthelot CS40407 63011 Clermont Ferrand cedex 01
  telephone: 04 73 31 95 95
  web: http://www.agefos-pme-auvergnerhonealpes.com
AGEFOS PME délégation interdépartementale Franche Comté:
  adresse: 2 rue de l'Industrie BP76337 25017 Besançon cedex
  telephone: 0820 42 00 51*
  web: http://www.agefos-pme-bfc.com
AGEFOS PME établissement Agefomat:
  adresse: 35 rue Froidevaux 75014 Paris
  telephone: 01 43 22 70 70
  web: http://www.agefomat.com
AGEFOS PME Grand Est - Territoire d'Alsace:
  adresse: 28 rue Kilbs BP145 Bischoffsheim 67214 Obernai cedex
  telephone: 03 88 49 41 51
  web: http://www.agefos-pme-grandest.com
AGEFOS PME Grand Est - Territoire de Champagne Ardenne:
  adresse: Centre d'affaires Santos Dumont bâtiment A8 BP286 51687 Reims cedex 2
  telephone: 03 26 83 50 90
  web: http://www.agefos-pme-grandest.com
AGEFOS PME Grand Est - Territoire de Lorraine:
  adresse: 3 rue de Berlange 57140 Woippy
  telephone: 03 87 32 03 90
  web: http://www.agefos-pme-grandest.com
AGEFOS PME Hauts de France:
  adresse: Pôle Jules Verne 15 rue de l'Ile Mystérieuse 80440 Boves
  telephone: 03 22 35 42 52
  web: http://www.agefos-pme-hautsdefrance.com
AGEFOS PME Ile de France:
  adresse: 11 rue Hélène 75849 Paris cedex 17
  web: http://www.agefos-pme-iledefrance.com
AGEFOS PME La Réunion:
  adresse: 32 rue de Cayenne BP310 97458 Saint Pierre cedex
  telephone: 02 62 96 11 80
  web: http://www.agefos-pme-reunion.com
AGEFOS PME Normandie:
  adresse: Citis 8 rue d'Atalante BP10268 14209 Hérouville Saint Clair cedex
  telephone: 02 31 50 17 17
  web: http://www.agefos-pme-normandie.com
AGEFOS PME Nouvelle Aquitaine:
  adresse: 7 avenue du Millac 33370 Artigues près Bordeaux
  telephone: 05 57 77 34 84
  web: http://www.agefos-pme-nouvelleaquitaine.com
AGEFOS PME Occitanie:
  adresse: Parc technologique du canal 14 avenue de l'Europe Bâtiment Houston BP42125 31521 Ramonville Saint Agne cedex
  telephone: 05 62 26 83 26
  web: http://www.agefos-pme-occitanie.com
AGEFOS PME Occitanie délégation interdépartementale Montpellier:
  adresse: quartier d'entreprise Tournezy plan Louis Jouvet bât A4 CS10015 34078 Montpellier cedex 3
  telephone: 04 67 07 04 50
  web: http://www.agefos-pme-occitanie.com
AGEFOS PME Pays de la Loire:
  adresse: 1 square de la Nouvelle France BP20548 49305 Cholet cedex
  telephone: 02 41 49 14 40
  web: http://www.agefos-pme-plpc.com
AGEFOS PME Provence Alpes Côte d'Azur:
  adresse: 146 rue Paradis CS30001 13294 Marseille cedex 06
  telephone: 04 91 14 08 80
  web: http://www.agefos-pme-paca.com
SPP Pêche et cultures marines:
  adresse: c/o Agefos Pme 7 rue Félix Le Dantec CS 83039 29334 Quimper cedex
  telephone: 02 98 97 26 52
  web: http://www.spppcm.fr
Opcalia Auvergne Rhône Alpes:
  adresse: 66 avenue Jean Mermoz BP8048 69351 Lyon cedex 08
  telephone: 04 78 77 06 87
  web: http://www.opcalia.com
Opcalia Bourgogne Franche Comté:
  adresse: 6 allée André Bourland BP67007 21070 Dijon cedex
  telephone: 03 80 77 85 75
  web: http://www.opcalia.com
Opcalia Bretagne:
  adresse: 4 bis allée du Bâtiment 35000 Rennes
  telephone: 02 23 20 00 20
  web: http://www.opcalia.com
Opcalia Centre Val de Loire:
  adresse: 22 rue Vallée Maillard BP80008 41913 Blois cedex 9
  telephone: 02 54 90 40 40
  web: http://www.opcalia.com
Opcalia Corse:
  adresse: Immeuble Bouttaud KM5 Route de Mezzavia 20190 Ajaccio
  telephone: 04 95 23 34 81
  web: http://www.opcalia.com
Opcalia département enseignement privé:
  adresse: 47 rue de la Victoire 75009 Paris
  telephone: 01 44 71 99 00
  web: http://www.opcalia.com
Opcalia département télécoms:
  adresse: 47 rue de la Victoire 75009 Paris
  telephone: 01 44 71 99 00
  web: http://www.opcalia.com
Opcalia département textiles, mode, cuirs:
  adresse: 47 rue de la Victoire 75009 Paris
  telephone: 01 48 24 10 59
  web: http://www.opcalia.com
Opcalia Grand Est:
  adresse: 18 rue des Métiers 68000 Colmar
  telephone: 03 89 21 64 70
  web: http://www.opcalia.com
Opcalia Guadeloupe:
  adresse: Immeuble Bravo Voie Verte BP2393 97188 Jarry cedex
  telephone: 05 90 60 18 13
  web: http://www.opcalia.com
Opcalia Guyane:
  adresse: 1897 route de Montjoly CS30810 97338 Cayenne cedex
  telephone: 05 94 28 45 64
  web: http://www.opcalia.com
Opcalia Hauts de France:
  adresse: 96 rue Nationale 59000 Lille
  telephone: 03 61 26 60 15
  web: http://www.opcalia.com
Opcalia Ile de France:
  adresse: 47 rue de la Victoire 75009 Paris
  telephone: 01 44 06 77 10
  web: http://www.opcalia.com
Opcalia Martinique:
  adresse: route Chateauboeuf 97200 FORT DE FRANCE
  telephone: 05 96 50 79 31
  web: http://www.opcalia.com
Opcalia Mayotte:
  adresse: 20 Immeuble Archipel ZI Kawéni BP469 97600 Mamoudzou
  telephone: 02 69 61 44 45
  web: http://www.opcalia.com
Opcalia Normandie:
  adresse: Immeuble le Galilée Technoparc des Bocquets 10 allée Enrico Fermi BP436 76235 Bois Guillaume cedex
  telephone: 02 35 12 17 17
  web: http://www.opcalia.com
Opcalia Nouvelle Aquitaine:
  adresse: Bureaux de Bordeaux Lac 1 Bâtiment 8 4 allée de Chavailles 33525 Bruges cedex
  telephone: 05 56 69 85 08
  web: http://www.opcalia.com
Opcalia Occitanie:
  adresse: Le Belvédère 11 boulevard des Récollets CS97802 31078 Toulouse cedex 4
  telephone: 05 61 14 51 61
  web: http://www.opcalia.com
Opcalia Pays de la Loire:
  adresse: Europarc la Chantrerie 8 rue Edouard Nignon CS30803 44308 Nantes cedex 3
  telephone: 02 40 99 38 00
  web: http://www.opcalia.com
Opcalia Provence Alpes Côte d'Azur:
  adresse: Les Carrés de l'Arc bâtiment C rond point du Canet 13590 Meyreuil
  telephone: 04 42 91 27 99
  web: http://www.opcalia.com
Opcalia Réunion:
  adresse: Centre d'affaires de la Mare 5 rue André Lardy Bâtiment C La Turbine 97438 Sainte Marie
  telephone: 02 62 90 23 45
  web: http://www.opcalia.com
# TODO: should we only keep main organisme info and then point to contact pages like http://www.moncepmonfongecif.fr/reseau/notre-presence
# or http://www.agefos-pme.com/fileadmin/user_upload/20-Partage/pdf/liste_regions.pdf ?
Fongecif:
  web: http://www.moncepmonfongecif.fr/
Fongecif Auvergne Rhône Alpes - Antenne Auvergne:
  adresse: Pôle Gambetta 4 avenue Marx Dormoy 63000 Clermont Ferrand
  telephone : 04 72 82 50 50
  web: http://www.fongecif-ara.fr
Fongecif Auvergne-Rhône-Alpes:
  adresse: Immeuble Le Premium 131 boulevard de Stalingrad 69624 Villeurbanne cedex
  telephone : 04 72 82 50 50
  web: http://www.fongecif-ara.fr
Fongecif Bourgogne Franche Comté - Site de Besançon:
  adresse: 15 rue Xavier Marmier 25000 Besançon
  telephone : 03 81 52 82 83
  web: http://www.fongecifbfc.org
Fongecif Bourgogne Franche Comté:
  adresse: Centre d'affaire Manouchka 6 rue Ez Penottes 21000 Dijon
  telephone : 03 80 53 22 44
  web: http://www.fongecifbfc.org
Fongecif Bretagne:
  adresse: 1A allée Ermengarde d'Anjou CS14440 35044 Rennes cedex
  telephone : 02 99 29 72 48
  web: http://www.fongecif-bretagne.org
Fongecif Centre Val de Loire:
  adresse: 931 rue de Bourges Olivet la Source CS 46037 45060 Orléans cedex 2
  telephone : 02 38 49 35 35
  web: http://www.fongecifcentre.com
Fongecif Corsica:
  adresse: Immeuble Sampolo bâtiment B 28 avenue Colonel Colonna d'Ornano 20000 Ajaccio
  telephone : 04 95 20 57 79
  web: http://www.fongecif-corsica.com
Fongecif Grand Est - Pôle territorial de Nancy:
  adresse: Le Trident 6 rue Cyfflé BP 20116 54003 Nancy cedex
  telephone : 03 83 30 82 80
  web: http://www.fongecif-grandest.org
Fongecif Grand Est - Pôle territorial de Reims:
  adresse: 33 bis rue Hincmar 51100 Reims
  telephone : 03 26 03 10 10
  web: http://www.fongecif-grandest.org
Fongecif Grand-Est:
  adresse: Pôle 2005 197 avenue d'Alsace 68027 Colmar cedex
  telephone : 03 89 20 17 50
  web: http://www.fongecif-grandest.org
Fongecif Guadeloupe:
  adresse: 73 les Hauts de Blachon 97122 Baie Mahault
  telephone : 05 90 32 10 33
  web: http://www.fongecif-guadeloupe.fr
Fongecif Guyane:
  adresse: 971 route de Montjoly 97354 Remire-Montjoly
  telephone : 05 94 35 75 87
  web: http://www.fongecif-guyane.com
Fongecif Hauts de France:
  adresse: 9 rue de l'Abbé Stahl TSA 80003 59705 Marcq en Baroeul cedex
  telephone : 03 59 61 62 63
  web: fongecif-hdf.fr
Fongecif Hauts de France - Antenne d'Amiens:
  adresse: 49 avenue d'Italie 80094 Amiens cedex 3
  telephone : 03 59 61 62 63
  web: fongecif-hdf.fr
Fongecif Île-de-France:
  adresse: 2 ter boulevard Saint Martin 75498 Paris cedex 10
  telephone : 01 44 10 58 58
  web: http://www.fongecif-idf.fr
Fongecif Martinique:
  adresse: Domaine de Montgérald 1 avenue Louis Domergue 97200 Fort de France
  telephone : 05 96 38 29 42
  web: http://www.fongecif-martinique.fr
Fongecif Normandie:
  adresse: Citis Immeuble Manager 15 avenue de Cambridge 14200 Hérouville Saint Clair
  telephone : 02 31 46 26 46
  web: http://www.fongecifnormandie.org
Fongecif Normandie - Antenne de Rouen:
  adresse: Immeuble Lavoisier 95 allée Alfred Nobel 76230 Bois Guillaume
  telephone : 02 35 07 95 55
  web: http://www.fongecifnormandie.org
Fongecif Nouvelle Aquitaine:
  adresse: Les bureaux du Lac II Immeuble M rue Robert Caumont 33049 Bordeaux cedex
  telephone : 09 72 61 55 50
  web: http://www.fongecifnouvelleaquitaine.org
Fongecif Nouvelle Aquitaine - Site de Limoges:
  adresse: 25 cours Jean Pénicaud 87000 Limoges
  telephone : 09 72 61 55 50
  web: http://www.fongecifnouvelleaquitaine.org
Fongecif Nouvelle Aquitaine - Site de Niort:
  adresse: 31 avenue de Verdun BP 70026 79001 Niort cedex
  telephone : 09 72 61 55 50
  web: http://www.fongecifnouvelleaquitaine.org
Fongecif Occitanie - Antenne Languedoc Roussillon:
  adresse: Parc d'activités la Peyrière 10 rue Robert Schuman 34430 Saint Jean de Vedas
  telephone : 0800 00 74 74*
  web: http://www.fongecif-occitanie.org
Fongecif Occitanie:
  adresse: Parc technologique du Canal 4 rue Giotto CS 72280 31522 Ramonville Saint Agne cedex
  telephone : 05 62 26 87 87
  web: http://www.fongecif-occitanie.org
Fongecif Pays de la Loire:
  adresse: 9 boulevard Alexandre Millerand BP 20135 44201 Nantes cedex 2
  telephone : 0810 19 16 80*
  web: http://www.fongecif-pdl.fr
Fongecif Provence Alpes Côte d'Azur:
  adresse: Les Docks Atrium 10.8 10 place de la Joliette CS 97212 13567 Marseille cedex 02
  telephone : 0805 850 100*
  web: http://www.fongecif-paca.com
Fongecif Réunion:
  adresse: Centre d'affaires de la Mare 5 rue André Lardy bât C La Turbine 97438 Sainte Marie
  telephone : 02 62 94 03 84
  web: http://www.fongecif-reunion.com
UNAGECIF:
  adresse: 48 boulevard des Batignolles 75017 PARIS
  telephone: 01 44 70 74 74
  web: http://www.unagecif.fr/
