# TODO : test and replace hard URL GIT and hard OLD_VERSION
# doc for use kaniko in gitlab env : https://docs.gitlab.com/ee/ci/docker/using_kaniko.html
# for registry and env var in general : https://docs.gitlab.com/ee/ci/variables/README.html#predefined-environment-variables
build:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/dockerfile_trefle --build-arg TREFLE_VERSION=$CI_COMMIT_TAG --build-arg TREFLE_GIT=https://git.beta.pole-emploi.fr/open-source/trefle.git --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
    - /kaniko/executor --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/dockerfile_web --build-arg TREFLE_VERSION=$CI_COMMIT_TAG --build-arg TREFLE_OLD_VERSION=0.6.1 --build-arg TREFLE_GIT=https://git.beta.pole-emploi.fr/open-source/trefle.git --destination $CI_REGISTRY_IMAGE:$CI_COMMIT_TAG
  only:
    - tags

test:
  image: python:3.6
  cache:
    paths:
    - ~/.cache/pip/

  before_script:
    - python setup.py develop
    - pip install -r requirements-dev.txt

  tags:
    - python
  stage: test
  script:
    - py.test -v --cov
    - behave -D coverage-format=long
