#TODO test docker image with https://github.com/aelsabbahy/goss
variables:
  TREFLE_OLD_VERSION: "api-v0.6.1"

api publish:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context ${CI_PROJECT_DIR}/docker --dockerfile $CI_PROJECT_DIR/docker/dockerfile_trefle --build-arg TREFLE_VERSION=$CI_COMMIT_TAG --build-arg TREFLE_GIT=${CI_PROJECT_URL} --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  only:
    - /^api-v[0-9.]+$/

backoffice publish:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context ${CI_PROJECT_DIR}/docker --dockerfile ${CI_PROJECT_DIR}/docker/dockerfile_backoffice --build-arg TREFLE_BACK_VERSION=${CI_COMMIT_TAG} --build-arg TREFLE_OLD_VERSION=${TREFLE_OLD_VERSION} --build-arg TREFLE_GIT=${CI_PROJECT_URL} --destination ${CI_REGISTRY_IMAGE}:${CI_COMMIT_TAG}
  only:
    - /^backoffice-v[0-9.]+$/

test backoffice image:
  variables:
    TREFLE_BACK_VERSION: backoffice-v0.0.2
  image:
    name: docker/compose
  stage: test
  script:
    - cd ${CI_PROJECT_DIR}/docker
    - docker-compose up -d --build trefle
    - docker ps
    - docker network
    - curl -fsSL https://goss.rocks/install | sh
    - GOSS_FILES_PATH=`pwd`/backoffice dgoss run -p 8888:80 -e "TREFLE_BACK_VERSION=$TREFLE_BACK_VERSION" -e "OLD_VERSION=$TREFLE_OLD_VERSION" -v `pwd`/backoffice/etc/nginx/sites-enabled:/etc/nginx/sites-enabled --link docker_trefle_1 --network docker_default ${CI_REGISTRY_IMAGE}:${TREFLE_BACK_VERSION}
  only:
    - /^test$/



test:
  image: python:3.6
  cache:
    paths:
    - ~/.cache/pip/
  before_script:
    - python setup.py develop
    - pip install -r requirements-dev.txt
  stage: test
  script:
    - py.test -v --cov
    - behave -D coverage-format=long
  only:
    - branches
    - master
