#TODO test docker image with https://github.com/aelsabbahy/goss

build-trefle:
  image:
    name: gcr.io/kaniko-project/executor:debug
    entrypoint: [""]
  stage: build
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --context ${CI_PROJECT_DIR}/docker --dockerfile $CI_PROJECT_DIR/docker/dockerfile_trefle --build-arg TREFLE_VERSION=$CI_COMMIT_TAG --build-arg TREFLE_GIT=${CI_PROJECT_URL} --destination ${CI_REGISTRY_IMAGE}:trefle-${CI_COMMIT_TAG}
  only:
    - /^trefle-v[0-9.]+$/
#build-web:
#  image:
#    name: gcr.io/kaniko-project/executor:debug
#    entrypoint: [""]
#  stage: build
#  script:
#    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
#    - /kaniko/executor --context ${CI_PROJECT_DIR}/docker --dockerfile $CI_PROJECT_DIR/docker/dockerfile_web --build-arg TREFLE_VERSION=$CI_COMMIT_TAG --build-arg TREFLE_GIT=${CI_PROJECT_URL} --destination ${CI_REGISTRY_IMAGE}:web-${CI_COMMIT_TAG}
#  only:
#    - tags

test:
  image: python:3.6
  cache:
    paths:
    - ~/.cache/pip/
  before_script:
    - python setup.py develop
    - pip install -r requirements-dev.txt
  stage: test
  script:
    - py.test -v --cov
    - behave -D coverage-format=long
  only:
    - branches
    - master
