image: python:latest

cache:
  paths:
  - ~/.cache/pip/

before_script:
  - python setup.py develop
  - pip install -r requirements-dev.txt

test:
  script:
  - py.test -v --cov
  - behave --lang fr -D coverage-format=long
