version: 1
config:
  - type: physical
    name: eth0
    subnets:
      - type: static
        ipv4: true
        address: {{ hostvars['trefle']['ansible_host'] }}
        netmask: 255.255.255.0
        gateway: 10.10.10.1
        control: auto
  - type: nameserver
    address: 8.8.8.8
