SI formation.cpf CONTIENT CODE_CPF_VAE:
    PLAFOND_FINANCIER = organisme.plafond_financier_vae
    PLAFOND_HORAIRE = organisme.plafond_horaire_vae
    TAUX_HORAIRE = organisme.taux_horaire_vae
SINON SI formation.cpf in CODES_CPF_CLEA:
    PLAFOND_FINANCIER = organisme.plafond_financier_clea
    PLAFOND_HORAIRE = organisme.plafond_horaire_clea
    TAUX_HORAIRE = organisme.taux_horaire_clea
SINON SI formation.eligible_cpf CONTIENT «COPANEF»:
    PLAFOND_FINANCIER = organisme.plafond_financier_copanef
    PLAFOND_HORAIRE = organisme.plafond_horaire_copanef
    TAUX_HORAIRE = organisme.taux_horaire_copanef
SINON SI formation.regions CONTIENT beneficiaire.entreprise.commune.region:
    PLAFOND_FINANCIER = organisme.plafond_financier_coparef
    PLAFOND_HORAIRE = organisme.plafond_horaire_coparef
    TAUX_HORAIRE = organisme.taux_horaire_coparef
SINON SI formations.naf CONTIENT beneficiaire.entreprise.naf:
    PLAFOND_FINANCIER = organisme.plafond_financier_cpne
    PLAFOND_HORAIRE = organisme.plafond_horaire_cpne
    TAUX_HORAIRE = organisme.taux_horaire_cpne
