SI scenario.nom CONTIENT «cpf»:
    ET constante.codes_cpf_vae CONTIENT formation.cpf:
        ALORS:
            - organisme.plafond_financier VAUT organisme.plafond_financier_vae
            - organisme.plafond_heures VAUT organisme.plafond_heures_vae
            - organisme.taux_horaire VAUT organisme.taux_horaire_vae
    ET constante.codes_cpf_clea CONTIENT formation.cpf:
        ALORS:
            - organisme.plafond_financier VAUT organisme.plafond_financier_clea
            - organisme.plafond_heures VAUT organisme.plafond_heures_clea
            - organisme.taux_horaire VAUT organisme.taux_horaire_clea
    ET formation.eligible_cpf CONTIENT «COPANEF»:
        ALORS:
            - organisme.plafond_financier VAUT organisme.plafond_financier_copanef
            - organisme.plafond_heures VAUT organisme.plafond_heures_copanef
            - organisme.taux_horaire VAUT organisme.taux_horaire_copanef
    ET formation.regions CONTIENT beneficiaire.entreprise.commune.region:
        ALORS:
            - organisme.plafond_financier VAUT organisme.plafond_financier_coparef
            - organisme.plafond_heures VAUT organisme.plafond_heures_coparef
            - organisme.taux_horaire VAUT organisme.taux_horaire_coparef
    ET formations.naf CONTIENT beneficiaire.entreprise.naf:
        ALORS:
            - organisme.plafond_financier VAUT organisme.plafond_financier_cpne
            - organisme.plafond_heures VAUT organisme.plafond_heures_cpne
            - organisme.taux_horaire VAUT organisme.taux_horaire_cpne
SI scenario.nom CONTIENT «cif»:
    ET organisme.nom = «FONGECIF»:
        ET beneficiaire.remuneration > constante.deux_smic ET beneficiaire.remuneration <= constante.trois_smic:
            ALORS:
                - organisme.plafond_financier VAUT organisme.plafond_financier_cif
                - organisme.taux_horaire VAUT organisme.taux_horaire_cif
                - organisme.reste_à_charge VAUT 0.05
        ET beneficiaire.remuneration > constante.trois_smic:
            ALORS:
                - organisme.plafond_financier VAUT organisme.plafond_financier_cif
                - organisme.taux_horaire VAUT organisme.taux_horaire_cif
                - organisme.reste_à_charge VAUT 0.10
    ET organisme.nom = «FAFSEA»:
        ALORS:
            - organisme.plafond_financier VAUT 18000
            - organisme.taux_horaire VAUT 27.45
    ET organisme.nom = «UNIFORMATION»:
        ET formation.taux_horaire_ttc < 18 OU formation.taux_horaire_ht < 15:
            ALORS:
                - organisme.plafond_financier VAUT 0
                - organisme.taux_horaire VAUT organisme.taux_horaire
    ET organisme.nom = «UNIFAF»:
        ALORS:
            - organisme.plafond_financier VAUT 0
    ET organisme.nom = «OPCALIM» OU organisme.nom = «AFDAS»:
        ALORS:
            - organisme.details_manquants VAUT OUI
