openapi: 3.0.0
info:
  title: Moteur de financement salariés
  version: 1.0.0
paths:
  /simulate:
    get:
      responses:
        200:
          description: Calcul effectué avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Resultat'
components:
  schemas:
    Resultat:
      required:
        - passed
        - failed
      properties:
        passed:
          $ref: '#/components/schemas/Financements'
        failed:
          $ref: '#/components/schemas/Financements'
    Financements:
      type: array
      items:
        $ref: "#/components/schemas/Financement"
