openapi: 3.0.0
info:
  title: Moteur de financement salariés
  version: 1.0.0
paths:
  /simulate:
    get:
      responses:
        200:
          description: Calcul effectué avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/scenario'
components:
  schemas: {}
