SI organisme.nom = «ACTALIANS»:
  ALORS:
    - organisme.taux_horaire_vae VAUT 75
    - organisme.plafond_horaire_vae VAUT 24
    - organisme.taux_horaire_clea VAUT 27
    - organisme.plafond_horaire_clea VAUT 150
    - organisme.taux_horaire_copanef VAUT 60
    - organisme.plafond_horaire_copanef VAUT 150
    - organisme.taux_horaire_coparef VAUT 0
    - organisme.plafond_horaire_coparef VAUT 0
    - organisme.taux_horaire_cpne VAUT 60
    - organisme.plafond_horaire_cpne VAUT 150
SI organisme.nom = «AFDAS»:
  ALORS:
    - organisme.taux_horaire_vae VAUT 100
    - organisme.plafond_horaire_vae VAUT formation.heures
    - organisme.taux_horaire_clea VAUT 35
    - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
    - organisme.taux_horaire_copanef VAUT 35
    - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
    - organisme.taux_horaire_coparef VAUT 35
    - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
    - organisme.taux_horaire_cpne VAUT 35
    - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
SI organisme.nom = «AGEFOS-PME»:
  ALORS:
    - organisme.taux_horaire_vae VAUT 50
    - organisme.plafond_horaire_vae VAUT formation.heures
    - organisme.taux_horaire_clea VAUT 50
    - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
    - organisme.taux_horaire_copanef VAUT 50
    - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
    - organisme.taux_horaire_coparef VAUT 50
    - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
    - organisme.taux_horaire_cpne VAUT 50
    - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
SI organisme.nom = «ANFA»:
  ALORS:
    - organisme.taux_horaire_vae VAUT 40
    - organisme.plafond_horaire_vae VAUT formation.heures
    - organisme.taux_horaire_clea VAUT 40
    - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
    - organisme.taux_horaire_copanef VAUT 40
    - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
    - organisme.taux_horaire_coparef VAUT 40
    - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
    # - organisme.taux_horaire_cpne VAUT "60 si intitulé comprend \\"CQP\\"\n50 pour toute autre certification"
    - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
SI organisme.nom = «CONSTRUCTYS»:
  ALORS:
    - organisme.taux_horaire_vae VAUT 80
    - organisme.plafond_horaire_vae VAUT formation.heures
    # - organisme.taux_horaire_clea VAUT "30\névaluation CLEA 60"
    - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
    # - organisme.taux_horaire_copanef VAUT "30\nsauf \n45 pour F°maintenance et conduite engin (formacode 31717) \n80 pourbilan de compétence (Certif Info n°93559) \n"
    - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
    # - organisme.taux_horaire_coparef VAUT "30\nsauf \n45 pour F°maintenance et conduite engin (formacode 31717) \n80 pour bilan de compétence (Certif Info n°93559) \n"
    - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
    # - organisme.taux_horaire_cpne VAUT "30\nsauf \n45 pour F°maintenance et conduite engin (formacode 31717) \n80 pour bilan de compétence (Certif Info n°93559) \n"
    - organisme.plafond_horaire_cpne:
SI organisme.nom = «FAFIEC»:
  ALORS:
    - organisme.taux_horaire_vae VAUT 100
    - organisme.plafond_horaire_vae VAUT formation.heures
    - organisme.taux_horaire_clea VAUT 40
    - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
    # - organisme.taux_horaire_copanef VAUT "40\n25 pour les formations de langue (formacode domaine 152)"
    - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
    # - organisme.plafond_financier_copanef VAUT 1750 pour les bilans de compétences (Certif Info n°93559)
    - organisme.taux_horaire_coparef VAUT 40
    - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
    - organisme.taux_horaire_cpne VAUT 40
    - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
SI organisme.nom = «FAFIH»:
  ALORS:
    - organisme.taux_horaire_vae VAUT 0
    - organisme.plafond_horaire_vae VAUT 0
    # - organisme.plafond_financier_vae VAUT "1 500 € maxi si la certification validée est un CQP\n2 500 € maxi si la certification validée est jusqu'à un niveau bac +2 \n3 500 € maxi si la certification validée est de nivea bac + 3 et plusI"
    - organisme.taux_horaire_clea VAUT 40
    - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
    - organisme.taux_horaire_copanef VAUT 40
    - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
    # - organisme.plafond_financier_copanef VAUT "2000 pour les bilans de compétences (Certif Info n°93559)\n750 pour les permis de conduire B (Code Certif Info n°54664)"
    - organisme.taux_horaire_coparef VAUT 40
    - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
    - organisme.taux_horaire_cpne VAUT 40
    - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
SI organisme.nom = «FAFSEA»:
  ALORS:
    - organisme.taux_horaire_vae VAUT formation.taux_horaire
    - organisme.plafond_horaire_vae VAUT formation.heures
    - organisme.taux_horaire_clea VAUT formation.taux_horaire
    - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
    - organisme.taux_horaire_copanef VAUT formation.taux_horaire
    - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
    - organisme.taux_horaire_coparef VAUT formation.taux_horaire
    - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
    - organisme.taux_horaire_cpne VAUT formation.taux_horaire
    - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
SI organisme.nom = «FAT-TT»:
  ALORS:
    - organisme.taux_horaire_vae VAUT 63
    - organisme.plafond_horaire_vae VAUT 24
    - organisme.plafond_financier_vae VAUT 1525
    - organisme.taux_horaire_clea VAUT 12
    - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
    # - organisme.taux_horaire_copanef VAUT "12\n60 pour TOEIC (Certif Info n°84168) ou BULATS (Certif Info n°95271, 84165, 84384)\n10 si intitulé comprend CACES"
    - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
    # - organisme.taux_horaire_coparef VAUT "12\n60 pour TOEIC (Certif Info n°84168) ou BULATS (Certif Info n°95271, 84165, 84384)\n10 si intitulé comprend CACES"
    - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
    # - organisme.taux_horaire_cpne VAUT "12\n60 pour TOEIC (Certif Info n°84168) ou BULATS (Certif Info n°95271, 84165, 84384)\n10 si intitulé comprend CACES"
    - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
SI organisme.nom = «FORCO»:
  ALORS:
    # idcc = commerce de détail non alimentaire
    - organisme.taux_horaire_vae VAUT 45
    - organisme.plafond_horaire_vae VAUT formation.heures
    - organisme.taux_horaire_clea VAUT 45
    - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
    - organisme.taux_horaire_copanef VAUT 45
    - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
    - organisme.taux_horaire_coparef VAUT 45
    - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
    - organisme.taux_horaire_cpne VAUT 45
    - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
  # (Code Certif Info n°54664)
  SI kkchose = «PermisB»:
    ALORS:
      - organisme.taux_horaire_copanef VAUT 40
      - organisme.plafond_financier_coparef VAUT 750
      - organisme.plafond_financier_copanef VAUT 750
  # TODO VAUT add PARMI/EN/DANS operator with list
  SI beneficiaire.entreprise.idcc = 0675,0468,1431,1487,2198,0043,1557,2162:
    ALORS:
      - organisme.taux_horaire_vae VAUT 40
      - organisme.taux_horaire_clea VAUT 40
      - organisme.taux_horaire_copanef VAUT 40
      - organisme.taux_horaire_coparef VAUT 40
      - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
      - organisme.taux_horaire_cpne VAUT 40
      - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
  SI idcc = 2216,2156,1044,1606:
    ALORS:
      - organisme.taux_horaire_vae VAUT 45
      - organisme.plafond_horaire_vae VAUT formation.heures
      - organisme.taux_horaire_clea VAUT 45
      - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
      - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
      - organisme.taux_horaire_coparef VAUT 45
      - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
      - organisme.taux_horaire_cpne VAUT 45
      - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
  SI beneficiaire.entreprise.idcc = 1517:
    ALORS:
      - organisme.taux_horaire_vae VAUT 50
      - organisme.plafond_horaire_vae VAUT formation.heures
      - organisme.taux_horaire_clea VAUT 50
      - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
      - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
      - organisme.taux_horaire_coparef VAUT 50
      - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
      - organisme.taux_horaire_cpne VAUT 50
      - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
SI organisme.nom = «INTERGROS»:
  ALORS:
    - organisme.taux_horaire_vae VAUT formation.taux_horaire
    - organisme.plafond_horaire_vae VAUT formation.heures
    - organisme.plafond_financier_vae VAUT 2000
    - organisme.taux_horaire_clea VAUT 18
    - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
    # - organisme.taux_horaire_copanef VAUT "30\nsi formation en liangue en FOAD 10"
    - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
    # - organisme.taux_horaire_coparef VAUT "30\nsi formation en liangue en FOAD 10"
    - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
    # - organisme.taux_horaire_cpne VAUT "30\nsi formation en liangue en FOAD 10"
    - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
SI organisme.nom = «OPCA-3-PLUS»:
  ALORS:
    - organisme.taux_horaire_vae VAUT formation.taux_horaire
    - organisme.plafond_horaire_vae VAUT formation.heures
    - organisme.taux_horaire_clea VAUT formation.taux_horaire
    - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
    - organisme.taux_horaire_copanef VAUT formation.taux_horaire
    - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
    - organisme.taux_horaire_coparef VAUT formation.taux_horaire
    - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
    - organisme.taux_horaire_cpne VAUT formation.taux_horaire
    - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
# SI organisme.nom = «OPCABAIA»:
#   SI idcc = 2335,1672,1801:
#     ALORS:
#       - organisme.taux_horaire_vae VAUT formation.taux_horaire
#       - organisme.plafond_horaire_vae VAUT formation.heures
#       - organisme.plafond_financier_vae VAUT 2500
#       - organisme.taux_horaire_clea VAUT formation.taux_horaire
#       - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
#       - organisme.plafond_financier_clea VAUT 10000
#       - organisme.taux_horaire_copanef VAUT "formation.taux_horaire\n"
#       - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
#       - organisme.plafond_financier_copanef VAUT "10 000 pour niv f°< ou = niveau 2\n16 000 pour niveau f°= niveau 1\n2100 pour bilan de compétences\n1500 pour permis B"
#       - organisme.taux_horaire_coparef VAUT formation.taux_horaire
#       - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
#       - organisme.plafond_financier_coparef VAUT "10 000 pour niv f°< ou = niveau 2\n16 000 pour niveau f°= niveau 1\n2100 pour bilan de compétences\n1500 pour permis B"
#       - organisme.taux_horaire_cpne VAUT formation.taux_horaire
#       - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
#       - organisme.plafond_financier_cpne VAUT "10 000 pour niv f°< ou = niveau 2\n16 000 pour niveau f°= niveau 1\n2100 pour bilan de compétences\n1500 pour permis B"
#   SI idcc VAUT 2120:
#     ALORS:
#       - organisme.taux_horaire_vae VAUT formation.taux_horaire
#       - organisme.plafond_horaire_vae VAUT formation.heures
#       - organisme.plafond_financier_vae VAUT 2500
#       - organisme.taux_horaire_clea VAUT formation.taux_horaire
#       - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
#       - organisme.plafond_financier_clea VAUT 2500
#       - organisme.taux_horaire_copanef VAUT "formation.taux_horaire\n37€ pour langues"
#       - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
#       # - organisme.plafond_financier_copanef VAUT "8 500/an\n2100 pour bilan de compétences\n1500 pour permis B\\"\n"
#       - organisme.taux_horaire_coparef VAUT formation.taux_horaire
#       - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
#       # - organisme.plafond_financier_coparef VAUT "8500/an\n2100 pour bilan de compétences\n1500 pour permis B\\""
#       - organisme.taux_horaire_cpne VAUT formation.taux_horaire
#       - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
#       - organisme.plafond_financier_cpne VAUT "12 000/an\n2100 pour bilan de compétences\n1500 pour permis B"
# SI organisme.nom = «OPCA-DEFI»:
#   SI idcc VAUT 0292:
#     ALORS:
#       - organisme.taux_horaire_vae VAUT 25
#       - organisme.plafond_horaire_vae VAUT formation.heures
#       - organisme.taux_horaire_clea VAUT 25
#       - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
#       - organisme.taux_horaire_copanef VAUT 25
#       - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
#       - organisme.taux_horaire_coparef VAUT 25
#       - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
#       - organisme.taux_horaire_cpne VAUT formation.taux_horaire
#       - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
#   SI idcc VAUT 0044:
#     ALORS:
#       - organisme.taux_horaire_vae VAUT taux horaire
#       - organisme.plafond_horaire_vae VAUT formation.heures
#       - organisme.plafond_financier_vae VAUT 5000
#       - organisme.taux_horaire_clea VAUT 35
#       - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
#       - organisme.taux_horaire_copanef VAUT "35\nformation.taux_horaire pour Cambridge English Business Certificates"
#       - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
#       - organisme.plafond_financier_copanef VAUT "1000 pour permis B\n3000 pour bilan de compétence"
#       - organisme.taux_horaire_coparef VAUT 35
#       - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
#       - organisme.taux_horaire_cpne VAUT formation.taux_horaire
#       - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
#   SI idcc VAUT 0076,1388:
#     ALORS:
#       - organisme.taux_horaire_vae VAUT taux horaire
#       - organisme.plafond_horaire_vae VAUT formation.heures
#       - organisme.taux_horaire_clea VAUT formation.taux_horaire
#       - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
#       - organisme.taux_horaire_copanef VAUT "\nformation.taux_horaire "
#       - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
#       - organisme.taux_horaire_coparef VAUT formation.taux_horaire
#       - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
#       - organisme.taux_horaire_cpne VAUT formation.taux_horaire
#       - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
#   SI idcc VAUT 1555:
#     ALORS:
#       - organisme.taux_horaire_vae VAUT taux horaire
#       - organisme.plafond_horaire_vae VAUT formation.heures
#       - organisme.taux_horaire_clea VAUT formation.taux_horaire
#       - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
#       - organisme.taux_horaire_copanef VAUT "\nformation.taux_horaire \n12€ pour langues"
#       - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
#       - organisme.taux_horaire_coparef VAUT "\nformation.taux_horaire \n12€ pour langues"
#       - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
#       - organisme.taux_horaire_cpne VAUT "\nformation.taux_horaire \n12€ pour langues"
#       - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
# SI organisme.nom = «OCPAIM»:
#   ALORS:
#     - organisme.taux_horaire_vae VAUT 62
#     - organisme.plafond_horaire_vae VAUT formation.heures
#     - organisme.taux_horaire_clea VAUT 45
#     - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
#     - organisme.taux_horaire_copanef VAUT 45
#     - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
#     - organisme.taux_horaire_coparef VAUT 45
#     - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
#     - organisme.taux_horaire_cpne VAUT 45
#     - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
# SI organisme.nom = «OPCALIA»:
#   ALORS:
#     - organisme.taux_horaire_vae VAUT 50
#     - organisme.plafond_horaire_vae VAUT formation.heures
#     - organisme.taux_horaire_clea VAUT 50
#     - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
#     - organisme.taux_horaire_copanef VAUT 50
#     - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
#     - organisme.taux_horaire_coparef VAUT 50
#     - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
#     - organisme.taux_horaire_cpne VAUT 50
#     - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
# SI organisme.nom = «OPCALIM»:
#   ALORS:
#     - organisme.taux_horaire_vae VAUT 50
#     - organisme.plafond_horaire_vae VAUT formation.heures
#     - organisme.plafond_financier_vae VAUT 8000
#     - organisme.taux_horaire_clea VAUT 50
#     - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
#     - organisme.plafond_financier_clea VAUT 8000
#     - organisme.taux_horaire_copanef VAUT 50
#     - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
#     - organisme.plafond_financier_copanef VAUT 8000
#     - organisme.taux_horaire_coparef VAUT 50
#     - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
#     - organisme.taux_horaire_cpne VAUT 50
#     - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
#     - organisme.plafond_financier_cpne VAUT 8000
# OPCA TRANSPORTS ET SI organisme.nom = «SERVICES»:
#   ALORS:
#     - organisme.taux_horaire_vae VAUT 57
#     - organisme.plafond_horaire_vae VAUT 21h
#     - organisme.plafond_financier_vae VAUT 400/jour
#     - organisme.taux_horaire_clea VAUT 15
#     - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
#     - organisme.taux_horaire_copanef VAUT 15
#     - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
#     - organisme.taux_horaire_coparef VAUT 15
#     - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
#     - organisme.taux_horaire_cpne VAUT 30
#     - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
# SI organisme.nom = «UNIFAF»:
#   ALORS:
#     - organisme.taux_horaire_vae VAUT 66.66
#     - organisme.plafond_horaire_vae VAUT formation.heures
#     - organisme.taux_horaire_clea VAUT 50
#     - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
#     - organisme.taux_horaire_copanef VAUT 50
#     - organisme.plafond_horaire_copanef VAUT beneficiaire.cpf
#     - organisme.taux_horaire_coparef VAUT 50
#     - organisme.plafond_horaire_coparef VAUT beneficiaire.cpf
#     - organisme.taux_horaire_cpne VAUT 50
#     - organisme.plafond_horaire_cpne VAUT beneficiaire.cpf
# SI organisme.nom = «UNIFORMATION»:
#   ALORS:
#     - organisme.taux_horaire_vae VAUT 56
#     - organisme.plafond_horaire_vae VAUT "72h si VAE visée est de niveau V\n24 h pour les autres niveaux visés"
#     - organisme.plafond_financier_vae VAUT "2500 si la VAE visée est de niveau V\n1750 pour les autres niveaux"
#     - organisme.taux_horaire_clea VAUT "40 si durée de formation <  70h\n25 si durée de formation > ou = 70h\n"
#     - organisme.plafond_horaire_clea:
#     - organisme.plafond_financier_clea VAUT "600 € pour les évaluations préalables\n300€ pour les évaluations finales"
#     - organisme.taux_horaire_coparef VAUT "40 si durée de formation <  70h\n25 si durée de formation > ou = 70h\n"
#     - organisme.plafond_horaire_coparef:
#     - organisme.taux_horaire_cpne VAUT 40
#     - organisme.plafond_horaire_cpne:
