constante:
  codes_financeur_pôle_emploi:
    description: ensemble des codes financeurs collectifs
    type: List[int]
    value: [2, 4, 6, 8, 9, 11, 12, 13, 15, 16]
  idcc_artisanat:
    description: ensemble des codes IDCC de l'artisanat
    type: List[int]
    value: [12345]
  codes_cpf_vae:
    description: liste des codes CPF identifiant une formation VAE
    type: List[int]
    value: [200]
  codes_cpf_clea:
    description: liste des codes CPF identifiant une formation CleA
    type: List[int]
    value: [201, 207, 208]
beneficiaire:
  droit_prive:
    description: être salarié d'une entreprise de droit privé
    type: bool
    source: beneficiaire
  cpf:
    description: solde du compte CPF
    type: int
    source: beneficiaire
  remuneration:
    description: Rémunération actuelle en euros
    type: int
    source: beneficiaire
  age:
    description: âge du beneficiaire
    type: int
    source: beneficiaire
  experience_professionelle:
    description: nombre de mois travaillés sur les 5 dernières années
    type: int
    source: beneficiaire
  mois_travailles_en_cdd:
    description: nombre de mois travaillés sur un contrat CDD sur les 12 derniers mois
    type: int
    source: beneficiaire
  entreprise:
    ape:
      description: l'identifiant NAF/APE de l'entreprise
      type: str
      source: routine.idcc2ape
    idcc:
      description: l'identifiant de convention collective de l'établissement
      type: str
      source: beneficiaire
    cpne:
      description: liste CPNE du secteur d'activité de l'entreprise
      type: liste de code CPF (trois ou quatre chiffre)
      source: routine.cpne
    commune:
      cp:
        description: code postale de la commune
        type: str
        source: beneficiaire
      insee:
        description: code INSEE de la commune de l'entreprise
        type: int
        source: routine.code_insee
      code_region:
        description: région de l'entreprise
        type: int
        source: routine.code_region
formation:
  code_financeur:
    description: code financeur
    type: List[int]
    source: catalogue
  tag_cpf:
    description: un ou plusieurs codes CPF
    type: List[int]
    source: catalogue
  eligible_cpf:
    description: liste des éditeurs d'éligibilité CPF (COPANEF, COPAREF, CPNE)
    type: List[str]
    source: catalogue
  regions:
    description: régions d'éligibilité si COPAREF dans les listes_eligibilite_cpf
    type: List[int]
    source: routine.formation_region
organisme:
  nom:
    type: str
  cpne:
    type: str
    source: routine
  copanef:
    type: bool
    source: routine
  coparef:
    type: str
    source: routine
  plafond_financier_vae:
    type: int
    source: routine.idcc2organisme
  plafond_financier_copanef:
    type: int
    source: routine.idcc2organisme
  taux_horaire_copanef:
    type: int
    source: routine.idcc2organisme
scenario:
  nom:
    type: str
    source: private
