constante:
  codes_financeur_collectif:
    description: ensemble des codes financeurs collectifs
    type: List[int]
    value: [2, 4, 6, 8, 9, 11, 12, 13, 15, 16]
  idcc_artisanat:
    description: ensemble des codes IDCC de l'artisanat
    type: List[int]
    value: [12345]
  codes_cpf_vae:
    description: liste des codes CPF identifiant une formation VAE
    type: List[int]
    value: [200]
  codes_cpf_clea:
    description: liste des codes CPF identifiant une formation CleA
    type: List[int]
    value: [201, 207, 208]
  deux_smic:
    type: int
    value: 2997
  trois_smic:
    type: int
    value: 2997
beneficiaire:
  droit_prive:
    description: être salarié d'une entreprise de droit privé
    type: bool
    source: beneficiaire
    label: bénéficiaire de droit privé
  cpf:
    description: solde du compte CPF
    type: int
    source: beneficiaire
    label: compte CPF du bénéficiaire
  remuneration:
    description: Rémunération actuelle en euros
    type: int
    source: beneficiaire
    label: rémunération du bénéficiaire
  age:
    description: âge du beneficiaire
    type: int
    source: beneficiaire
  experience_professionelle:
    description: nombre de mois travaillés sur les 5 dernières années
    type: int
    source: beneficiaire
  mois_travailles_en_cdd:
    description: nombre de mois travaillés sur un contrat CDD sur les 12 derniers mois
    type: int
    source: beneficiaire
  contrat:
    description: type de contrat du bénéficiaire
    type: str
    source: beneficiaire
  anciennete_entreprise_actuelle:
    description: ancienneté en mois dans l'entreprise actuelle
    type: int
    source: beneficiaire
  experience_professionnelle:
    description: nombre de mois travaillés dans les X dernières années
    type: int
    source: beneficiaire
  entreprise:
    naf:
      description: l'identifiant NAF/APE de l'entreprise
      type: str
      source: routine.idcc2naf
    idcc:
      description: l'identifiant de convention collective de l'établissement
      # TODO: uniformize the type (int but 0234 so str?)
      type: int
      source: beneficiaire
      label: IDCC de l'établissement du bénéficiaire
    cpne:
      description: liste CPNE du secteur d'activité de l'entreprise
      type: liste de code CPF (trois ou quatre chiffre)
      source: routine.cpne
    cp:
      description: code postale de la commune
      type: str
      source: beneficiaire
    insee:
      description: code INSEE de la commune de l'entreprise
      type: int
      source: routine.code_insee
    region:
      description: région de l'entreprise
      type: int
      source: routine.code_region
formation:
  code_financeur:
    description: code financeur
    type: List[int]
    source: catalogue
  tag_cpf:
    description: un ou plusieurs codes CPF
    type: List[int]
    source: catalogue
  copanef:
    description: cette formation est au catalogue COPANEF
    type: bool
    source: routine.extraire_copanef
    label: formation éligible COPANEF
  eligible_cpf:
    description: liste des éditeurs d'éligibilité CPF (COPANEF, COPAREF, CPNE)
    type: List[str]
    source: catalogue
  regions:
    description: régions d'éligibilité si COPAREF dans les listes_eligibilite_cpf
    type: List[int]
    source: routine.formation_region
  heures:
    type: int
    source: private
    label: durée en heures de la formation
  mois:
    type: int
    source: private
    label: durée en mois de la formation
  taux_horaire:
    type: int
    source: private
    label: taux horaire de la formation
  taux_horaire_ttc:
    type: int
    source: private
  taux_horaire_ht:
    type: int
    source: private
  cpf:
    description: code CPF de la formation (plusieurs? cf tag_cpf)
    type: int
    source: catalogue
    label: code CPF de la formation
  codes_naf:
    description: codes NAF des différents CPNE
    type: List[int]
    source: routine.naf_from_formation
organisme:
  nom:
    type: str
  cpne:
    type: str
    source: routine
  copanef:
    type: bool
    source: routine
  coparef:
    type: str
    source: routine
  plafond_financier:
    type: int
    source: private
  plafond_horaire:
    type: int
    source: private
  taux_horaire:
    type: int
    source: private
scenario:
  nom:
    type: str
    source: private
scenarios:
  eligibles:
    description: liste des identifiants de scénarios éligibles
    type: List[str]
    source: private
  non_eligibles:
    description: liste des identifiants de scénarios non éligibles
    type: List[str]
    source: private
