constante:
  codes_financeur_collectif:
    description: ensemble des codes financeurs collectifs
    type: List[int]
    value: [2, 4, 6, 8, 9, 11, 12, 13, 15, 16]
    label: codes financeurs collectifs
  idcc_artisanat:
    description: ensemble des codes IDCC de l'artisanat
    type: List[int]
    value: [12345]
    label: codes IDCC de l'artisanat
  codes_cpf_vae:
    description: liste des codes CPF identifiant une formation VAE
    type: List[int]
    value: [200]
    label: codes CPF VAE
  codes_cpf_clea:
    description: liste des codes CPF identifiant une formation CleA
    type: List[int]
    value: [201, 207, 208]
    label: codes CPF CleA
  deux_smic:
    type: integer
    format: int32
    value: 2997
    label: deux fois le SMIC
  trois_smic:
    type: integer
    format: int32
    value: 2997
    label: trois fois le SMIC
beneficiaire:
  droit_prive:
    description: le bénéficiaire est salarié d'une entreprise de droit privé
    type: boolean
    public: true
    required: true
    label: bénéficiaire de droit privé
  solde_cpf:
    description: solde du compte CPF du bénéficiaire
    type: integer
    format: int32
    public: true
    required: true
    label: solde CPF du bénéficiaire
  remuneration:
    description: Rémunération actuelle en euros
    type: integer
    format: int32
    public: true
    required: true
    label: rémunération du bénéficiaire
  age:
    description: âge du beneficiaire
    type: integer
    format: int32
    public: true
    label: âge du bénéficiaire
  experience_professionelle:
    description: nombre de mois travaillés sur les 5 dernières années
    type: integer
    format: int32
    public: true
    label: expérience professionnelle du bénéficiaire dans les cinq dernières années
  mois_travailles_en_cdd:
    description: nombre de mois travaillés sur un contrat CDD sur les 12 derniers mois
    type: integer
    format: int32
    public: true
    label: nombre de mois travaillés par le bénéficiaire dans la dernière année
  contrat:
    description: type de contrat du bénéficiaire
    type: string
    public: true
    label: type de contrat du bénéficiaire
  anciennete_entreprise_actuelle:
    description: ancienneté en mois dans l'entreprise actuelle
    type: integer
    format: int32
    public: true
    label: ancienneté du bénéficiaire dans son entreprise
  entreprise:
    naf:
      description: l'identifiant NAF/APE de l'entreprise
      type: string
      public: true
      label: code NAF de l'établissement du bénéficiaire
    idcc:
      description: l'identifiant de convention collective de l'établissement
      # TODO: uniformize the type (int but 0234 so str?)
      type: integer
      format: int32
      public: true
      label: IDCC de l'établissement du bénéficiaire
    region:
      description: région de l'entreprise
      type: integer
      format: int32
      public: true
      label: région de l'établissement du bénéficiaire
formation:
  numero:
    description: identifiant INTERCARIF de la formation
    type: string
    public: true
    label: identifiant de la formation
  code_financeur:
    description: code financeur
    type: List[int]
    source: catalogue
    label: code financeur de la formation
  eligible_copanef:
    description: cette formation est au catalogue COPANEF
    type: boolean
    source: routine.extraire_copanef
    label: formation éligible COPANEF
  regions_coparef:
    description: régions d'éligibilité si COPAREF dans les listes_eligibilite_cpf
    type: List[int]
    source: routine.formation_region
    label: régions éligibles COPAREF
  heures:
    type: integer
    format: int32
    label: durée en heures de la formation
  mois:
    type: integer
    format: int32
    label: durée en mois de la formation
  taux_horaire:
    type: integer
    format: int32
    label: taux horaire de la formation
  taux_horaire_ttc:
    type: integer
    format: int32
    label: taux horaire TTC de la formation
  taux_horaire_ht:
    type: integer
    format: int32
    label: taux horaire HT de la formation
  cpf:
    description: code CPF de la formation (plusieurs? cf tag_cpf)
    type: integer
    format: int32
    source: catalogue
    label: code CPF de la formation
  codes_naf:
    description: codes NAF des différents CPNE
    type: List[int]
    source: routine.naf_from_formation
    label: codes NAF CPNE éligibles
financement:
  nom:
    type: string
    public: true
    label: nom du financement
  # Do not use "type" for now, it's used as duck typing.
  genre:
    type: string
    label: type de financement
  remuneration:
    type: integer
    format: int32
    public: true
    nullable: true
    label: rémunération possible
  prise_en_charge:
    type: integer
    format: int32
    public: true
    nullable: true
    label: montant de prise en charge possible
  plafond_financier:
    type: integer
    format: int32
    label: plafond financier applicable
  plafond_horaire:
    type: integer
    format: int32
    label: plafond horaire applicable
  taux_horaire:
    type: integer
    format: int32
    label: taux horaire applicable
  reste_a_charge:
    type: number
    format: float
    label: reste à charge applicable
  organisme:
    nom:
      public: true
      type: string
      label: nom de l'organisme
financements:
  eligibles:
    description: liste des identifiants de scénarios éligibles
    type: List[str]
    label: financements possibles
  non_eligibles:
    description: liste des identifiants de scénarios non éligibles
    type: List[str]
