SI le nom de l'organisme est «FONGECIF»
    SI le nom du financement contient «CIF»
        SI la rémunération du bénéficiaire est supérieure à deux fois le SMIC ET la rémunération du bénéficiaire est inférieure à trois fois le SMIC
            ALORS le plafond financier applicable vaut 18000
            ALORS le taux horaire applicable vaut 27.45
            ALORS le reste à charge applicable est égal à 0.05
        SI la rémunération du bénéficiaire est supérieure à trois fois le SMIC
            ALORS le plafond financier applicable vaut 18000
            ALORS le taux horaire applicable vaut 27.45
            ALORS le reste à charge applicable est égal à 0.10
