version: "3.7"
services:
  trefle:
    restart: unless-stopped
    image: registry.beta.pole-emploi.fr/open-source/trefle:${VERSION}
    volumes:
      - ./log/trefle:/srv/log
    environment:
        - LBF_CHARMAP=${LBF_CHARMAP}
        - CATALOG_USER=${CATALOG_USER}
        - CATALOG_KEY=${CATALOG_KEY}
        - CATALOG_URL=${CATALOG_URL}
    healthcheck:
      test: curl -sFS http://localhost:8000/ || exit 1
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 30s
  #version majeur précédente
  trefle-old:
    restart: unless-stopped
    image: registry.beta.pole-emploi.fr/open-source/trefle:${OLD_VERSION}
    volumes:
      - ./log/trefle-old:/srv/log
    environment:
        - LBF_CHARMAP=${LBF_CHARMAP}
        - CATALOG_USER=${CATALOG_USER}
        - CATALOG_KEY=${CATALOG_KEY}
        - CATALOG_URL=${CATALOG_URL}
        - GITLAB_TOKEN=${GITLAB_TOKEN}
        - COMMIT_AUTHORIZED=${COMMIT_AUTHORIZED}
    healthcheck:
      test: curl -sFS http://localhost:8000/ || exit 1
      interval: 5s
      timeout: 3s
      retries: 3
      start_period: 30s
  web:
    restart: unless-stopped
    image:  registry.beta.pole-emploi.fr/open-source/trefle:${BACK_VERSION}
    depends_on:
      - trefle
      - trefle-old
    volumes:
      - ./backoffice/etc/nginx/sites-enabled:/etc/nginx/sites-enabled
      - ./log/nginx:/var/log/nginx
    dns:
      - 1.1.1.1
    ports:
      - ${PORT:-80}:80
    environment:
      - VERSION=${VERSION}
      - HOST=trefle
      - OLD_VERSION=${OLD_VERSION}
      - OLD_HOST=trefle-old
