FROM node:10 AS back_app_node

ARG TREFLE_GIT

ARG TREFLE_BACK_VERSION
RUN git clone -b ${TREFLE_BACK_VERSION} ${TREFLE_GIT} /srv/trefle && \
    chown -R www-data: /srv/trefle && \
    chmod -R u+rwx /srv/trefle && \
    cd /srv/trefle/backoffice && \
    npm install && \
    npm run build


FROM ubuntu:bionic

LABEL maintainer="labonneformation@pole-emploi.fr"

ENV LANG C.UTF-8
ENV DEBIAN_FRONTEND noninteractive
ENV TZ=Europe/Paris

RUN apt-get update && apt-get -y install \
                                 apt-utils\
                                 software-properties-common\
                                 tzdata \
                                 unzip \
                                 nginx \
                                 vim \
                                 bzip2 \
                                 cron \
                                 rsyslog \
                                 logrotate \
                                 iptables \
                                 git \
                                 dnsutils



COPY --from=back_app_node /srv/trefle/backoffice/dist /srv/trefle/backoffice
COPY --from=back_app_node /srv/trefle/trefle/explorer /srv/trefle/legacy-backoffice

ARG TREFLE_GIT
ARG TREFLE_OLD_VERSION
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone && \
    sed -i 's#\(\s\+\)invoke-rc.d.*#\1kill -USR1 $(cat /var/run/nginx.pid)#' /etc/logrotate.d/nginx && \
    git clone -b ${TREFLE_OLD_VERSION} ${TREFLE_GIT} /srv/trefle-old && \
    chown -R www-data: /srv/trefle-old && \
    chmod -R u+rwx /srv/trefle-old

CMD service nginx start; \
    cron -f
