SI le nom de l'organisme est «AGEFOS_PME»
    ALORS le taux horaire applicable vaut 50
    ALORS le plafond horaire applicable est égal au compte CPF du bénéficiaire
    SI le code CPF de la formation fait partie des codes CPF VAE
        ALORS le plafond horaire applicable est égal à la durée en heures de la formation
