SI organisme.nom = «ANFA»:
  ALORS:
    - organisme.taux_horaire_clea VAUT 40
    - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
  SI constante.codes_cpf_vae CONTIENT formation.cpf:
    ALORS:
      - organisme.taux_horaire VAUT 40
      - organisme.plafond_horaire VAUT formation.heures
  SI formation.codes_naf CONTIENT beneficiaire.entreprise.naf:
    ALORS:
      - organisme.taux_horaire VAUT 50
    # 60 si intitulé comprend \\"CQP\\"\n50 pour toute autre certification
    # SI kkchose CONTIENT «CPQ»:
    #   ALORS:
    #     - organisme.taux_horaire VAUT 60
