SI le nom de l'organisme est «FAFIEC»
    ALORS le taux horaire applicable vaut 40
    ALORS le plafond horaire applicable est égal au compte CPF du bénéficiaire
    # ALORS organisme.taux_horaire_copanef VAUT "40\n25 pour les formations de langue (formacode domaine 152)"
    # ALORS organisme.plafond_financier_copanef VAUT 1750 pour les bilans de compétences (Certif Info n°93559)
  SI le code CPF de la formation fait partie des codes CPF VAE
      ALORS le taux horaire applicable vaut 100
      ALORS le plafond horaire applicable est égal à la durée en heures de la formation
