SI le nom de l'organisme est «FAFIH»
    ALORS le taux horaire applicable vaut 40
    ALORS le plafond horaire applicable est égal au solde CPF du bénéficiaire
    # ALORS organisme.plafond_financier_vae VAUT "1 500 € maxi si la certification validée est un CQP\n2 500 € maxi si la certification validée est jusqu'à un niveau bac +2 \n3 500 € maxi si la certification validée est de nivea bac + 3 et plusI"
    # ALORS organisme.plafond_financier_copanef VAUT "2000 pour les bilans de compétences (Certif Info n°93559)\n750 pour les permis de conduire B (Code Certif Info n°54664)"
    SI le code CPF de la formation fait partie des codes CPF VAE
        ALORS le taux horaire applicable vaut 0
        ALORS le plafond horaire applicable vaut 0
