SI organisme.nom = «FAT-TT»:
  ALORS:
    - organisme.taux_horaire_clea VAUT 12
    - organisme.plafond_horaire_clea VAUT beneficiaire.cpf
  # - organisme.taux_horaire_copanef VAUT "12\n60 pour TOEIC (Certif Info n°84168) ou BULATS (Certif Info n°95271, 84165, 84384)\n10 si intitulé comprend CACES"
  # - organisme.taux_horaire_coparef VAUT "12\n60 pour TOEIC (Certif Info n°84168) ou BULATS (Certif Info n°95271, 84165, 84384)\n10 si intitulé comprend CACES"
  # - organisme.taux_horaire_cpne VAUT "12\n60 pour TOEIC (Certif Info n°84168) ou BULATS (Certif Info n°95271, 84165, 84384)\n10 si intitulé comprend CACES"
  SI constante.codes_cpf_vae CONTIENT formation.cpf:
    ALORS:
      - organisme.taux_horaire VAUT 63
      - organisme.plafond_horaire VAUT 24
      - organisme.plafond_financier VAUT 1525
