SI le nom de l'organisme est «INTERGROS»
    ALORS le plafond horaire applicable est égal au compte CPF du bénéficiaire
    # ALORS organisme.taux_horaire_copanef VAUT "30\nsi formation en liangue en FOAD 10"
    # ALORS organisme.taux_horaire_coparef VAUT "30\nsi formation en liangue en FOAD 10"
    # ALORS organisme.taux_horaire_cpne VAUT "30\nsi formation en liangue en FOAD 10"
  SI le code CPF de la formation fait partie des codes CPF VAE
      ALORS le taux horaire applicable est égal au taux horaire de la formation
      ALORS le plafond horaire applicable est égal à la durée en heures de la formation
      ALORS le plafond financier applicable vaut 2000
  SI le code CPF de la formation fait partie des codes CPF CleA
      ALORS le taux horaire applicable vaut 18
