SI organisme.nom = «OCPAIM»:
  ALORS:
    - organisme.taux_horaire VAUT 45
    - organisme.plafond_horaire VAUT beneficiaire.cpf
  SI constante.codes_cpf_vae CONTIENT formation.cpf:
    ALORS:
      - organisme.taux_horaire VAUT 62
      - organisme.plafond_horaire VAUT formation.heures
