SI le nom de l'organisme est «OPCA_TRANSPORTS_ET_SERVICES»
    ALORS le taux horaire applicable est égal à 15
    ALORS le plafond horaire applicable est égal au compte CPF du bénéficiaire
  SI le code CPF de la formation fait partie des codes CPF VAE
      ALORS le taux horaire applicable vaut 57
      ALORS le plafond horaire applicable vaut 21
      # ALORS organisme.plafond_financier_journalier VAUT 400
  SI le code NAF de l'établissement du bénéficiaire fait partie des codes NAF CPNE éligibles
      ALORS le taux horaire applicable vaut 30
