SI organisme.nom = «UNIFORMATION»:
  SI scenario.nom CONTIENT «cpf»:
    ALORS:
      - organisme.taux_horaire VAUT 40
    SI constante.codes_cpf_vae CONTIENT formation.cpf:
      ALORS:
        - organisme.taux_horaire VAUT 56
        # - organisme.plafond_horaire_vae VAUT "72h si VAE visée est de niveau V\n24 h pour les autres niveaux visés"
      # - organisme.plafond_financier_vae VAUT "2500 si la VAE visée est de niveau V\n1750 pour les autres niveaux"
      # - organisme.taux_horaire_clea VAUT "40 si durée de formation <  70h\n25 si durée de formation > ou = 70h\n"
      # - organisme.plafond_financier_clea VAUT "600 € pour les évaluations préalables\n300€ pour les évaluations finales"
      # - organisme.taux_horaire_coparef VAUT "40 si durée de formation <  70h\n25 si durée de formation > ou = 70h\n"
  SI scenario.nom CONTIENT «cpf»:
      SI formation.taux_horaire_ttc < 18 OU formation.taux_horaire_ht < 15:
          ALORS:
              - organisme.plafond_financier VAUT 0
              - organisme.taux_horaire VAUT organisme.taux_horaire
