cpf:
  genre: CPF
  description: le compte personnel de formation (CPF) permet au salarié d'acquérir des droits et de les mobiliser pour financer des actions de formation tout au long de sa vie professionnelle.
  temps_de_travail:
    nom: CPF sur son temps de travail
    demarches: Pour une formation se déroulant sur le temps de travail, il est nécessaire de demander l'accord de l'employeur Assurez vous que votre compte personnel de formation est activé sur http://www.moncompteformation.gouv.fr/ . Contacter votre employeur pour bénéficier gratuitement d’un conseil en évolution professionnelle et valider votre projet de formation et son financement CPF.
  hors_temps_de_travail:
    nom: CPF hors temps de travail
    demarches: Pour une formation se déroulant en dehors du temps de travail, il n'est pas nécessaire de demander l'accord de l'employeur. Assurez-vous que votre compte personnel de formation est activé sur http://www.moncompteformation.gouv.fr/ Contactez directement votre Opca {organisme.nom} pour bénéficier gratuitement d’un conseil en évolution professionnelle et valider votre projet de formation et son financement CPF.
cif:
  genre: CIF
  cdi:
    pendant_temps_de_travail:
      nom: CIF sur le temps de travail en situation de CDI
    hors_temps_de_travail:
      nom: CIF hors temps de travail en situation de CDI
  cdd:
    pendant_temps_de_travail:
      nom: CIF sur le temps de travail en situation de CDD
    hors_temps_de_travail:
      nom: CIF hors temps de travail en situation de CDD
  interim:
    pendant_temps_de_travail:
      nom: CIF sur le temps de travail en situation de contrat interim
    hors_temps_de_travail:
      nom: CIF hors temps de travail en situation de contrat interim
  intermitent:
    pendant_temps_de_travail:
      nom: CIF sur le temps de travail pour les intermitents
    hors_temps_de_travail:
      nom: CIF hors temps de travail pour les intermitents
