# FIXME CIF vs cdi (clash with Pointer loading enum label)
CPF sur son temps de travail:
  tags: [CPF, sur son temps de travail]
  rules: salarié
CPF hors temps de travail:
  tags: [CPF, hors temps de travail]
  rules: salarié
CPF demandeur d'emploi:
  tags: [CPF, DE]
  rules: CPF DE
CIF CDI sur son temps de travail:
  tags: [CIF, cdi, sur son temps de travail]
  rules: CIF
CIF CDI hors temps de travail:
  tags: [CIF, cdi, hors temps de travail]
  rules: CIF
CIF CDD sur son temps de travail:
  tags: [CIF, cdd, sur son temps de travail]
  rules: CIF
CIF CDD hors temps de travail:
  tags: [CIF, cdd, hors temps de travail, DE]
  rules: CIF
CIF intérim sur son temps de travail:
  tags: [CIF, interim, sur son temps de travail]
  rules: CIF
CIF intérim hors temps de travail:
  tags: [CIF, interim, hors temps de travail, DE]
  rules: CIF
CIF intermittents hors temps de travail:
  tags: [CIF, intermittent, hors temps de travail]
  rules: CIF
Période de professionnalisation sur son temps de travail:
  tags: [période de professionnalisation, sur son temps de travail]
  rules: salarié
  ressources:
  - https://www.service-public.fr/particuliers/vosdroits/F13516
Plan de formation sur son temps de travail:
  tags: [plan de formation, sur son temps de travail]
  rules: salarié
  ressources:
  - https://www.service-public.fr/particuliers/vosdroits/F11267
Aide individuelle à la formation:
  tags: [AIF, DE]
  rules: AIF
Aide individuelle à la formation artisan:
  tags: [AIF, artisan, DE]
  rules: AIF artisan
"Formation en alternance : contrat d'apprentissage":
  tags: [contrat apprentissage, alternance, DE]
  rules: contrat d'apprentissage
"Formation en alternance : contrat de professionnalisation":
  tags: [contrat professionnalisation, alternance, DE]
  rules: contrat de professionnalisation
Formations avant embauche (AFPR, POEI):
  tags: [AFPR, POEI, DE]
  rules: POEI
Préparation opérationnelle à l'emploi collective:
  tags: [POEC, DE]
  rules: POEC
Financement individuel Agefiph:
  tags: [Agefiph, DE]
  rules: Agefiph
Fonds d'aide aux jeunes:
  tags: [FAJ, DE, jeune]
  rules: FAJ
Action de formation collective financée par la région:
  tags: [DE, région, collectif]
  rules: action collective
Action de formation collective financée par Pôle emploi:
  tags: [DE, PE, collectif]
  rules: action collective
Action de formation collective financée par l'Agefiph:
  tags: [DE, TH, collectif]
  rules: action collective
Action de formation collective financée par le conseil départemental:
  tags: [DE, département, collectif]
  rules: action collective
Action de formation collective financée par l'État:
  tags: [DE, État, collectif]
  rules: action collective
Chèque formation:
  tags: [DE, région, individuel]
  rules: DE Bretagne
  ressources:
  - https://www.seformerenbretagne.fr
Formations du domaine sanitaire et social:
  tags: [DE, région, individuel, branche]
  rules: DE Bretagne
  ressources:
  - https://www.bretagne.bzh/jcms/c_15456/fr/les-formations-sanitaires-et-sociales
Programme Bretagne Formation:
  tags: [DE, région, collectif]
  rules: DE Bretagne
  ressources:
  - https://www.seformerenbretagne.fr
Accès aux premiers savoirs - ETAPS:
  tags: [DE, région, collectif]
  rules: DE Provence-Alpes-Côte d'Azur
ETAQ (Espaces territoriaux à la qualification):
  tags: [DE, région, collectif]
  rules: DE Provence-Alpes-Côte d'Azur
École de la deuxième chance (E2C):
  tags: [DE, jeune, E2C]
  rules: DE Auvergne-Rhône-Alpes
Action projets individuels (API):
  tags: [DE, API]
  rules: DE Auvergne-Rhône-Alpes
Programme Enseignement supérieur (ESUP):
  tags: [DE, ESUP]
  rules: DE Auvergne-Rhône-Alpes
Contrat d'aide et retour à l'emploi durable (CARED):
  tags: [DE, CARED]
  rules: DE Auvergne-Rhône-Alpes
Contrat d'aide et retour à l'emploi durable collectif:
  tags: [DE, CARED]
  rules: DE Auvergne-Rhône-Alpes
Programmation compétences premières (PCP):
  tags: [DE, PCP]
  rules: DE Auvergne-Rhône-Alpes
Programme régional qualifiant:
  tags: [DE]
  rules: DE Auvergne-Rhône-Alpes
Projets collectifs régionaux:
  tags: [DE]
  rules: DE Auvergne-Rhône-Alpes
Programme régional sanitaire et social:
  tags: [DE]
  rules: DE Auvergne-Rhône-Alpes
Programme régional sanitaire et social - ambulancier:
  tags: [DE]
  rules: DE Auvergne-Rhône-Alpes
Aide à la VAE:
  tags: [DE, VAE]
  rules: DE Auvergne-Rhône-Alpes
