# FIXME CIF vs cdi (clash with Pointer loading enum label)
CPF sur son temps de travail:
  tags: [CPF, sur son temps de travail]
  racine: organisme paritaire.rules
CPF hors temps de travail:
  tags: [CPF, hors temps de travail]
  racine: organisme paritaire.rules
CPF demandeur d'emploi:
  tags: [CPF, DE]
  racine: CPF DE.rules
CIF CDI sur son temps de travail:
  tags: [CIF, cdi, sur son temps de travail]
  racine: organisme paritaire.rules
CIF CDI hors temps de travail:
  tags: [CIF, cdi, hors temps de travail]
  racine: organisme paritaire.rules
CIF CDD sur son temps de travail:
  tags: [CIF, cdd, sur son temps de travail]
  racine: organisme paritaire.rules
CIF CDD hors temps de travail:
  tags: [CIF, cdd, hors temps de travail, DE]
  racine: organisme paritaire.rules
CIF intérim sur son temps de travail:
  tags: [CIF, interim, sur son temps de travail]
  racine: organisme paritaire.rules
CIF intérim hors temps de travail:
  tags: [CIF, interim, hors temps de travail, DE]
  racine: organisme paritaire.rules
CIF intermittents hors temps de travail:
  tags: [CIF, intermittent, hors temps de travail]
  racine: organisme paritaire.rules
Période de professionnalisation sur son temps de travail:
  tags: [période de professionnalisation, sur son temps de travail]
  racine: organisme paritaire.rules
  ressources:
  - https://www.service-public.fr/particuliers/vosdroits/F13516
Plan de formation sur son temps de travail:
  tags: [plan de formation, sur son temps de travail]
  racine: organisme paritaire.rules
  ressources:
  - https://www.service-public.fr/particuliers/vosdroits/F11267
Aide individuelle à la formation:
  tags: [AIF, DE]
  racine: région du bénéficiaire
Aide individuelle à la formation artisan:
  tags: [AIF, artisan, DE]
  racine: région du bénéficiaire
"Formation en alternance : contrat d'apprentissage":
  tags: [contrat apprentissage, alternance, DE]
  racine: région du bénéficiaire
"Formation en alternance : contrat de professionnalisation":
  tags: [contrat professionnalisation, alternance, DE]
  racine: région du bénéficiaire
Formations avant embauche (AFPR, POEI):
  tags: [AFPR, POEI, DE]
  racine: région du bénéficiaire
Préparation opérationnelle à l'emploi collective:
  tags: [POEC, DE]
  racine: région du bénéficiaire
Financement individuel Agefiph:
  tags: [Agefiph, DE]
  racine: région du bénéficiaire
Fonds d'aide aux jeunes:
  tags: [FAJ, DE, jeune]
  racine: région du bénéficiaire
Action de formation collective financée par la région:
  tags: [DE, région, collectif, AFC]
  racine: région du bénéficiaire
Action de formation collective financée par Pôle emploi:
  tags: [DE, PE, collectif, AFC]
  racine: région du bénéficiaire
Action de formation collective financée par l'Agefiph:
  tags: [DE, TH, collectif, AFC]
  racine: région du bénéficiaire
Action de formation collective financée par le conseil départemental:
  tags: [DE, département, collectif, AFC]
  racine: région du bénéficiaire
Action de formation collective financée par l'État:
  tags: [DE, État, collectif, AFC]
  racine: région du bénéficiaire
Chèque formation:
  tags: [DE, région, individuel]
  racine: Bretagne.rules
  ressources:
  - https://www.seformerenbretagne.fr
Formations du domaine sanitaire et social:
  tags: [DE, région, individuel, branche]
  racine: Bretagne.rules
  ressources:
  - https://www.bretagne.bzh/jcms/c_15456/fr/les-formations-sanitaires-et-sociales
Programme Bretagne Formation:
  tags: [DE, région, collectif]
  racine: Bretagne.rules
  ressources:
  - https://www.seformerenbretagne.fr
Accès aux premiers savoirs:
  sigle: ETAPS
  tags: [DE, région, collectif]
  racine: Provence-Alpes-Côte d'Azur.rules
Espaces territoriaux à la qualification:
  tags: [DE, région, collectif, ETAQ]
  sigle: ETAQ
  racine: Provence-Alpes-Côte d'Azur.rules
École de la deuxième chance:
  sigle: E2C
  tags: [DE, jeune, E2C]
  racine: Auvergne-Rhône-Alpes.rules
Action projets individuels:
  sigle: API
  tags: [DE, API]
  racine: Auvergne-Rhône-Alpes.rules
Programme Enseignement supérieur:
  sigle: ESUP
  tags: [DE, ESUP]
  racine: Auvergne-Rhône-Alpes.rules
Contrat d'aide et retour à l'emploi durable:
  sigle: CARED
  tags: [DE, CARED]
  racine: Auvergne-Rhône-Alpes.rules
Contrat d'aide et retour à l'emploi durable collectif:
  tags: [DE, CARED]
  racine: Auvergne-Rhône-Alpes.rules
Programmation compétences premières:
  sigle: PCP
  tags: [DE, PCP]
  racine: Auvergne-Rhône-Alpes.rules
Programme régional qualifiant:
  tags: [DE]
  racine: Auvergne-Rhône-Alpes.rules
Projets collectifs régionaux:
  tags: [DE]
  racine: Auvergne-Rhône-Alpes.rules
Programme régional sanitaire et social:
  tags: [DE]
  racine: Auvergne-Rhône-Alpes.rules
Programme régional sanitaire et social - ambulancier:
  tags: [DE]
  racine: Auvergne-Rhône-Alpes.rules
Aide à la VAE:
  tags: [DE, VAE]
  racine: Auvergne-Rhône-Alpes.rules
Action collective financée par la Collectivité territoriale de Corse:
  tags: [DE, collectif, région]
  racine: Corse.rules
Programme sanitaire et social:
  tags: [DE, collectif, région]
  racine: Corse.rules
Action collective financée par la région:
  tags: [DE, collectif, région]
  racine: Pays de la Loire.rules
  ressources:
    - http://www.paysdelaloire.fr/politiques-regionales/formation-professionnelle
Action collective sanitaire et social financée par la région et Pôle emploi:
  tags: [DE, collectif, région]
  racine: Pays de la Loire.rules
  ressources:
    - http://www.paysdelaloire.fr/politiques-regionales/formation-professionnelle
Formations sanitaire et social d'aide-soignant ou d'auxiliaire de puériculture région Île-de-France:
  tags: [DE, région, collectif]
  racine: Île-de-France.rules
Formations sanitaire et social post-bac région Île-de-France:
  tags: [DE, région, collectif]
  racine: Île-de-France.rules
Programme régional qualifiant compétences:
  tags: [DE, région, collectif]
  racine: Île-de-France.rules
Chéquier unique VAE Région Ile-de-France:
  tags: [DE, région, individuel]
  racine: Île-de-France.rules
Paris formation pour l'emploi:
  tags: [DE, département, collectif]
  racine: Île-de-France.rules
Accès des demandeurs d’emploi aux métiers agricoles:
  sigle: ADEMA
  tags: [DE, collectif, ADEMA]
  racine: région du bénéficiaire
Programme de formations collectives financées par le Conseil régional de Normandie:
  tags: [DE, région, collectif]
  racine: Normandie.rules
Une formation, un emploi - individuel:
  tags: [DE, région, individuel]
  racine: Normandie.rules
Une formation, un emploi - collectif:
  tags: [DE, région, collectif]
  racine: Normandie.rules
Qualif individuel:
  tags: [DE, région, individuel]
  racine: Normandie.rules
VAE Normandie:
  tags: [DE, VAE]
  racine: Normandie.rules
Programme régional de formation:
  sigle: PRF
  tags: [DE, collectif, PRF]
  racine: Nouvelle-Aquitaine.rules
