CPF:
  eligible: false
  description: Le compte personnel de formation (CPF) permet au salarié d'acquérir des droits et de les mobiliser pour financer des actions de formation tout au long de sa vie professionnelle.
  sur son temps de travail:
    nom: CPF sur son temps de travail
    demarches: |-
      Pour une formation se déroulant sur le temps de travail, il est nécessaire de demander l'accord de l'employeur.
      Assurez-vous que votre compte personnel de formation est activé sur http://www.moncompteformation.gouv.fr/.
      Contacter votre employeur pour bénéficier gratuitement d’un conseil en évolution professionnelle et valider votre projet de formation et son financement CPF.
  hors temps de travail:
    nom: CPF hors temps de travail
    demarches: |-
      Pour une formation se déroulant en dehors du temps de travail, il n'est pas nécessaire de demander l'accord de l'employeur.
      Assurez-vous que votre compte personnel de formation est activé sur http://www.moncompteformation.gouv.fr/.
      Contactez directement votre Opca {nom} pour bénéficier gratuitement d’un conseil en évolution professionnelle et valider votre projet de formation et son financement CPF.
CIF:
  eligible: false
  description: |-
    Le congé individuel de formation (CIF) permet au salarié  de suivre, à son initiative et à titre individuel, une  formation, dans le but de :
      - se reconvertir
      - ou acquérir un niveau supérieur de qualification ou une 1re qualification
      - ou se perfectionner
      - ou s'ouvrir plus largement à la culture et à la vie sociale.
    Attention, un delai de franchise s'applique aux salariés ayant déjà bénéficié d'un CIF. Il est au minimum  de 6 mois et  au maximum de 6 ans
  demarches: |-
    Pour une formation se déroulant sur le temps de travail, il est nécessaire de demander l'accord de l'employeur.
    Attention aux délais pour faire cette demande : trois mois pour une formation de six mois et plus, deux mois pour les autres.
    Pour une formation hors temps de travail, il n'y a pas d'autorisation d'absence à demander. Retirer auprès de l'organisme {nom} un dossier de demande de prise en charge.
    Vérifier les délais pour faire cette demande. Indiquer votre accord pour compléter, si besoin, le financement de la formation avec votre Compte Personnel de Formation.
  CDI:
    sur son temps de travail:
      nom: CIF CDI sur son temps de travail
    hors temps de travail:
      nom: CIF CDI hors temps de travail
  CDD:
    demarches: |-
      Si la formation se déroule pendant votre temps de travail, il est nécessaire d'avoir une autorisation d'absence de votre employeur.
      Attention aux délais pour faire cette demande : trois mois pour une formation de six mois et plus, deux mois pour les autres.
      Retirer auprès de l'organisme {nom} un dossier de demande de prise en charge.
      Vérifier les délais pour faire cette demande.
      Indiquer votre accord pour compléter, si besoin, le financement de la formation avec votre Compte Personnel de Formation.
      Démarrer la formation au plus tard 12 mois après la fin de votre CDD.
    sur son temps de travail:
      nom: CIF CDD sur son temps de travail
    hors temps de travail:
      nom: CIF CDD hors temps de travail
  interim:
    demarches: |-
      Faite une demande d’autorisation d’absence auprès de l'agence d'intérim avec laquelle vous avez conclu votre CDI intérimaire, en cours de contrat ou dans un délai de trois maximum après la fin de votre contrat.
      Prenez contact avec l'organisme {nom} pour monter le dossier de financement.
      La formation doit démarrer au plus tard 12 mois après le dépôt de la demande d'absence.
      Dans certains cas, l'organisme peut participer aux frais de transport et/ou d’hébergement. Faire la demande dans le dossier CIF ou au plus tard un mois après la fin de la formation. Les frais de repas ne sont pas pris en charge par l'organisme.
    sur son temps de travail:
      nom: CIF intérim sur son temps de travail
    hors temps de travail:
      nom: CIF intérim hors temps de travail
  intermittent:
    sur son temps de travail:
      nom: CIF intermittents sur son temps de travail
      demarches: |-
        Contacter les conseillers Afdas pour vous informer sur les différents dispositifs de formation et vous accompagner dans l’élaboration de votre dossier :
        Si vous résidez en région Ile-de-France ou Centre, appelez le 01 44 78 38 39.
        Pour les autres régions, contactez votre délégation régionale Afdas.
        L’Afdas étudie les demandes de prise en charge des frais de déplacement et d’hébergement sous réserve que les frais annexes soient dûment justifiés, la demande de prise en charge soit complétée et retournée à l’Afdas en même temps
        que votre dossier CIF.
        Si votre demande est acceptée, il vous appartiendra d’informer votre conseiller Pôle Emploi de votre entrée en stage.
        Attention aux critères d'accès
        Sur les 220 jours de travail ou cachets requis pour demander un CIF, vous devez justifier de :
        - Pour les artistes interprètes et musiciens : 60 jours ou cachets répartis sur les 24 derniers mois ou 30 jours ou cachets répartis sur les 12 derniers mois
        - Pour les techniciens du spectacle vivant ou réalisateurs : 88 jours de travail ou cachets répartis sur les 24 derniers mois ou 44 jours ou cachets répartis sur les 12 derniers mois
        - Pour les techniciens de l’audiovisuel : 130 jours de travail ou cachets répartis sur les 24 derniers mois ou 65 jours de travail ou cachets répartis sur les 12 derniers mois.
        Délai de carence en mois = durée en heures du dernier CIF /12.
    hors temps de travail:
      nom: CIF intermittents hors temps de travail
