openapi: 3.0.0
info:
  title: Moteur de financement salariés
  version: 1.0.0
paths:
  /financement:
    post:
      responses:
        200:
          description: Calcul effectué avec succès
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Collection'
        422:
          description: Les informations sont invalides
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
        400:
          description: Le format de la requête est invalide
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Errors'
components:
  schemas:
    Collection:
      required:
        - collection
      properties:
        collection:
          $ref: '#/components/schemas/Financements'
    Financements:
      type: array
      items:
        $ref: "#/components/schemas/Financement"
    Errors:
      type: object
      additionalProperties:
        type: string
