Actalians:
  adresse: 4 rue du Colonel Driant 75046 Paris cedex 01
  telephone: 01 53 00 86 00
  web: www.actalians.fr
Afdas:
  adresse: 66 rue Stendhal CS 32016 75990 Paris cedex 20
  telephone: 01 44 78 39 39
  web: www.afdas.com
ANFA:
  adresse: 41-49 rue de la Garenne 92315 Sèvres cedex
  telephone: 01 41 14 16 18
  web: www.anfa-auto.fr
Constructys:
  adresse: 32 rue René Boulanger CS 60033 75483 Paris cedex 10
  telephone: 01 82 83 95 00
  web: www.constructys.fr
FAF.TT:
  adresse: 14 rue Riquet 75940 Paris cedex 19
  telephone: 01 53 35 70 00
  web: www.faftt.fr
Fafiec:
  adresse: 25 quai Panhard et Levassor 75013 Paris
  telephone: 0811 021 112*
  web: www.fafiec.fr
Fafih:
  adresse: 3 rue de la Ville l'Evêque 75008 Paris
  telephone: 01 40 17 20 20
  web: www.fafih.com
FAFSEA:
  adresse: 153 rue de la Pompe CS 60742 75179 Paris cedex 16
  telephone: 01 70 38 38 38
  web: www.fafsea.com
Forco:
  adresse: 251 boulevard Pereire 75852 Paris cedex 17
  telephone: 01 55 37 41 51
  web: www.forco.org
Intergros:
  adresse: Immeuble Le Mercure - Bâtiment C 13 boulevard du Mont d'Est CS 10022 93192 Noisy le Grand cedex
  telephone: 01 78 37 14 00
  web: www.intergros.com
OPCA 3+:
  adresse: 55 rue de Châteaudun 75009 Paris
  telephone: 01 82 71 48 48
  web: www.opca3plus.fr
OPCA DEFI:
  adresse: 5-7 avenue du Général de Gaulle 94166 Saint Mandé cedex
  telephone: 01 58 64 18 30
  web: www.opcadefi.fr
OPCA Transports et Services:
  adresse: 66 rue des Archives 75140 Paris cedex 3
  telephone: 01 53 91 34 34
  web: www.opca-transports.com
OPCABAIA:
  adresse: 14-18 rue Ballu 75009 Paris
  telephone: 01 55 50 49 50
  web: www.opcabaia.fr
OPCAIM:
  adresse: 120 boulevard de Courcelles 75849 Paris cedex 17
  telephone: 01 40 54 22 73
  web: www.opcaim.com
OPCALIM:
  adresse: 20 place des Vins de France CS 11240 75603 Paris cedex 12
  telephone: 01 40 19 41 00
  web: www.opcalim.org
Unifaf:
  adresse: 31 rue Anatole France 92300 Levallois Perret
  telephone: 01 49 68 10 10
  web: www.unifaf.fr
Uniformation:
  adresse: 43 boulevard Diderot 75012 Paris
  telephone: 01 53 02 13 13
  web: www.uniformation.fr
AGEFOS PME:
  adresse: 187 quai de Valmy 75010 Paris
  telephone: 01 44 90 46 46
  web: www.agefos-pme.com
Opcalia:
  adresse: 47 rue de la Victoire 75009 Paris
  telephone: 01 44 71 99 00
  web: www.opcalia.com
Fongecif:
  adresse: TODO
  telephone: TODO
  web: http://www.moncepmonfongecif.fr/
