cpf:
  organisme: routine.organisme_financeur_cpf
  taux_de_prise_en_charge: routine.taux_de_prise_en_charge_cpf
  temps_de_travail:
    nom: Financement CPF sur le temps de travail
    description: le compte personnel de formation (CPF) permet au salarié d'acquérir des droits et de les mobiliser pour financer des actions de formation tout au long de sa vie professionnelle.
    demarches: Pour une formation se déroulant sur le temps de travail, il est nécessaire de demander l'accord de l'employeur Assurez vous que votre compte personnel de formation est activé sur http://www.moncompteformation.gouv.fr/ . Contacter votre employeur pour bénéficier gratuitement d’un conseil en évolution professionnelle et valider votre projet de formation et son financement CPF.
    remuneration: beneficiaire.remuneration
  hors_temps_de_travail:
    nom: Financement CPF hors temps de travail
    demarches: Pour une formation se déroulant en dehors du temps de travail, il n'est pas nécessaire de demander l'accord de l'employeur. Assurez-vous que votre compte personnel de formation est activé sur http://www.moncompteformation.gouv.fr/ Contacter directement votre Opca {organisme.nom} pour bénéficier gratuitement d’un conseil en évolution professionnelle et valider votre projet de formation et son financement CPF.
    remuneration: 0
cif:
  organisme: routine.organisme_financeur_cif
  cdi:
    pendant_temps_de_travail:
      nom: Financement CIF sur le temps de travail en situation de CDI
      remuneration: routine.calcul_remuneration_cif
    hors_temps_de_travail:
      nom: Financement CIF hors temps de travail en situation de CDI
      remuneration: 0
  cdd:
    pendant_temps_de_travail:
      nom: Financement CIF sur le temps de travail en situation de CDD
      remuneration: routine.calcul_remuneration_cif
    hors_temps_de_travail:
      nom: Financement CIF hors temps de travail en situation de CDD
      remuneration: 0
  interim:
    pendant_temps_de_travail:
      nom: Financement CIF sur le temps de travail en situation de contrat interim
      remuneration: routine.calcul_remuneration_cif
    hors_temps_de_travail:
      nom: Financement CIF hors temps de travail en situation de contrat interim
      remuneration: 0
  intermitent:
    pendant_temps_de_travail:
      nom: Financement CIF sur le temps de travail pour les intermitents
      remuneration: routine.calcul_remuneration_cif
    hors_temps_de_travail:
      nom: Financement CIF hors temps de travail pour les intermitents
      remuneration: 0
