constante:
  codes_financeur_individuel:
    description: ensemble des codes financeur individuel
    type: array
    items:
      type: integer
    value: [0, 5, 10]
    label: codes financeur individuel
  codes_financeur_collectif:
    description: ensemble des codes financeurs collectifs
    type: array
    items:
      type: integer
    value: [2, 4, 6, 8, 9, 11, 12, 13, 15, 16]
    label: codes financeur collectif
  idcc_artisanat:
    description: ensemble des codes IDCC de l'artisanat
    type: array
    items:
      type: string
      format: idcc
    value: ["1596", "1638", "1722A", "1758", "1779", "2032", "2194", "2195", "2267", "2585"]
    label: codes IDCC de l'artisanat
  codes_cpf_vae:
    description: liste des codes CPF identifiant une formation VAE
    type: array
    items:
      type: integer
    value: [200]
    label: codes CPF VAE
  codes_cpf_clea:
    description: liste des codes CPF identifiant une formation CleA
    type: array
    items:
      type: integer
    value: [201, 207, 208]
    label: codes CPF CleA
  # https://www.service-public.fr/particuliers/vosdroits/F2300
  deux_smic:
    type: integer
    format: int32
    value: 2997
    label: deux fois le SMIC
  trois_smic:
    type: integer
    format: int32
    value: 4495
    label: trois fois le SMIC
  quatre_smic:
    type: integer
    format: int32
    value: 5994
    label: quatre fois le SMIC
  domaine_formacode_langue:
    description: le domaine FORMACODE des formations en langue
    type: integer
    value: 152
    label: domaine FORMACODE langues
  codes_permis_b:
    type: array
    items:
      type: integer
    value: [54664]
    label: codes CERTIFINFO pour un permis B
  codes_bilan_de_competences:
    type: array
    items:
      type: integer
    value: [93559]
    label: codes CERTIFINFO pour un bilan de compétences
  codes_bulats:
    type: array
    items:
      type: integer
    value: [95271, 84165, 84384]
    label: codes CERTIFINFO BULATS
  codes_bec:
    type: array
    items:
      type: integer
    value: [84166, 98623]
    label: codes CERTIFINFO BEC
  codes_toeic:
    type: array
    items:
      type: integer
    value: [84168]
    label: codes CERTIFINFO TOEIC
  codes_caces:
    type: array
    items:
      type: integer
    value: [55673, 55674, 55675, 55676, 55677, 55803, 55804, 55805, 55806,55807, 55808, 55809,55810, 55811, 55812, 55813, 55814, 55815, 55816, 55817, 55818, 55819, 55820, 55822, 55821, 55823, 55824, 55825, 55826, 55827, 84700, 84449, 84700, 84715, 85312, 85338]
    label: codes CERTIFINFO CACES
beneficiaire:
  droit_prive:
    description: le bénéficiaire est salarié d'une entreprise de droit privé
    type: boolean
    public: true
    required: true
    label: bénéficiaire de droit privé
    gender: masculine
  solde_cpf:
    description: solde du compte CPF du bénéficiaire
    type: integer
    format: int32
    public: true
    label: solde CPF du bénéficiaire
    gender: masculine
  remuneration:
    description: Rémunération actuelle en euros
    type: integer
    format: remuneration
    public: true
    required: true
    label: rémunération du bénéficiaire
  age:
    description: âge du beneficiaire
    type: integer
    format: int32
    public: true
    label: âge du bénéficiaire
    gender: masculine
  experience_professionnelle:
    description: nombre de mois travaillés sur les 5 dernières années
    type: integer
    format: int32
    public: true
    label: expérience professionnelle du bénéficiaire dans les cinq dernières années
  mois_travailles_en_cdd:
    description: nombre de mois travaillés sur un contrat CDD sur les 12 derniers mois
    type: integer
    format: int32
    public: true
    label: nombre de mois travaillés par le bénéficiaire dans la dernière année
    gender: masculine
  jours_travailles:
    description: nombre de jours travaillés dans les cinq dernières années (pour les intermittents)
    type: integer
    format: int32
    public: true
    label: nombre de jours travaillés par le bénéficiaire dans les cinq dernières années
    gender: masculine
  contrat:
    description: type de contrat du bénéficiaire
    type: string
    public: true
    required: true
    enum:
      cdd: CDD
      cdi: CDI
      intermittent: intermittent
      interim: intérimaire
    label: type de contrat du bénéficiaire
    gender: masculine
  anciennete_entreprise_actuelle:
    description: ancienneté en mois dans l'entreprise actuelle
    type: integer
    format: int32
    public: true
    label: ancienneté du bénéficiaire dans son entreprise
  entreprise:
    naf:
      description: l'identifiant NAF/APE de l'entreprise
      type: string
      format: naf
      pattern: ^\d{2}\.?\d{2}[a-zA-Z]$
      public: true
      label: code NAF de l'établissement du bénéficiaire
      gender: masculine
    idcc:
      description: l'identifiant de convention collective de l'établissement
      type: string
      format: idcc
      public: true
      required: true
      label: IDCC de l'établissement du bénéficiaire
      gender: masculine
    commune:
      description: code INSEE de la commune de l'établissement du bénéficiaire
      type: string
      public: true
      # required: true  # Make me required when LBF is ready
      pattern: ^(2[AB]|[0-9]{2})[0-9]{3}$
      label: code INSEE de la commune de l'établissement du bénéficiaire
      gender: masculine
    region:
      description: région de l'entreprise
      type: string
      label: région de l'établissement du bénéficiaire
      enum:
        '01': Guadeloupe
        '02': Martinique
        '03': Guyane
        '04': La Réunion
        '06': Mayotte
        '11': Île-de-France
        '24': Centre-Val de Loire
        '27': Bourgogne-Franche-Comté
        '28': Normandie
        '32': Nord-Pas-de-Calais-Picardie
        '44': Alsace-Champagne-Ardenne-Lorraine
        '52': Pays de la Loire
        '53': Bretagne
        '75': Aquitaine-Limousin-Poitou-Charentes
        '76': Languedoc-Roussillon-Midi-Pyrénées
        '84': Auvergne-Rhône-Alpes
        '93': Provence-Alpes-Côte d'Azur
        '94': Corse
    opca:
      description: L'OPCA auquel est rattaché l'établissement du bénéficiaire. Optionnel, habituellement déduit de l'IDCC.
      type: string
      format: opca
      public: true
      nullable: true
      label: OPCA de l'établissement du bénéficiaire
      gender: masculine
    opacif:
      description: L'OPACIF auquel est rattaché l'établissement du bénéficiaire. Optionnel, habituellement déduit de l'IDCC.
      type: string
      format: opacif
      public: true
      nullable: true
      label: OPACIF de l'établissement du bénéficiaire
      gender: masculine
    iae:
      description: définit si c'est une entreprise d'insertion par l'activité économique
      type: boolean
      label: entreprise d'insertion par l'activité économique
formation:
  numero:
    description: identifiant INTERCARIF de la formation
    type: string
    public: true
    label: identifiant de la formation
  codes_financeur:
    description: codes des organismes financeurs de la formation
    type: array
    format: set
    items:
      type: integer
    source: catalogue
    xpath: //organisme-financeur/code-financeur/child::text()
    label: codes financeur de la formation
    gender: masculine
    number: plural
  eligible_copanef:
    description: cette formation est au catalogue COPANEF
    type: boolean
    source: catalogue
    xpath: boolean(//extras[@info="eligibilite-cpf"]/extra[@info="france-entiere"][text()="1"]/../extra[@info="inter-branche"][text()="1"])
    label: formation éligible COPANEF
  regions_coparef:
    description: régions d'éligibilité si COPAREF dans les listes_eligibilite_cpf
    type: array
    format: set
    items:
      type: string
    source: catalogue
    xpath: //extras[@info="eligibilite-cpf"]/extra[@info="region"]/child::text()
    label: régions éligibles COPAREF
  codes_formacode:
    type: array
    items:
      type: integer
    source: catalogue
    xpath: //domaine-formation/code-FORMACODE/child::text()
    label: liste des codes FORMACODE de la formation
  domaines_formacode:
    description: domaines (trois premiers caractères des codes) FORMACODE de la formation
    type: array
    format: set
    items:
      type: integer
      format: domaine_formacode
    xpath: //domaine-formation/code-FORMACODE/child::text()
    source: catalogue
    label: liste des domaines FORMACODE de la formation
  code_certifinfo:
    type: integer
    format: int32
    source: catalogue
    xpath: number(//certification/code-CERTIFINFO/child::text())
    default: null
    label: code CERTIFINFO de la formation
    gender: masculine
  code_rncp:
    type: integer
    format: int32
    source: catalogue
    xpath: number(//certification/code-RNCP/child::text())
    label: code RNCP de la formation
    gender: masculine
  heures:
    type: integer
    format: int32
    default: 0
    source: catalogue
    xpath: number(//nombre-heures-total/child::text())
    label: durée en heures de la formation
  mois:
    type: integer
    format: int32
    # Sane default to prevent division by zero.
    # TODO: should we raise instead and log?
    default: 1
    label: durée en mois de la formation
  semaines:
    type: integer
    format: int32
    # Sane default to prevent division by zero.
    default: 1
    label: durée en semaines de la formation
  duree_hebdomadaire:
    type: integer
    format: int32
    default: 0
    label: durée hebdomadaire de la formation
  prix_horaire:
    type: integer
    format: float
    default: 0
    source: catalogue
    xpath: //prix-horaire-TTC/child::text()
    label: prix horaire de la formation
    description: prix horaire TTC de la formation
    gender: masculine
  prix_total:
    type: integer
    format: float
    source: catalogue
    xpath: //prix-total-TTC/child::text()
    label: prix total de la formation
    description: prix total TTC de la formation
    gender: masculine
  prix_horaire_ttc:
    type: integer
    format: float
    label: prix horaire TTC de la formation
  prix_horaire_ht:
    type: integer
    format: float
    label: prix horaire HT de la formation
  codes_cpf:
    description: codes CPF de la formation
    type: array
    format: set
    items:
      type: integer
      format: int32
    source: catalogue
    xpath: //extras[@info="eligibilite-cpf"]/@numero
    label: liste des codes CPF de la formation
  codes_naf:
    description: codes NAF des différents CPNE
    type: array
    format: set
    items:
      type: string
      format: naf
    source: catalogue
    xpath: //extras[@info="eligibilite-cpf"]/extra[@info="branche"]/child::text()
    label: codes NAF CPNE éligibles
    number: plural
  objectif_general_formation:
    description: code AIF de la formation (http://lheo.gouv.fr/langage#dict-AIS)
    label: code AIF de la formation
    type: integer
    formation: int32
    source: catalogue
    default: null
    xpath: number(//objectif-general-formation/child::text())
  debut:
    description: date de début de la formation
    label: date de début de la formation
    type: string
    format: date
    source: catalogue
    xpath: string((//periode/debut)[1]/child::text())
  fin:
    description: date de fin de la formation
    label: date de fin de la formation
    type: string
    format: date
    source: catalogue
    xpath: string((//periode/fin)[1]/child::text())
  foad:
    type: boolean
    source: catalogue
    xpath: boolean(//modalites-enseignement[text()="2"])
    label: formation ouverte à distance
  toeic:
    type: boolean
    source: catalogue
    label: formation TOEIC
  bulats:
    type: boolean
    source: catalogue
    label: formation BULATS
  caces:
    type: boolean
    source: catalogue
    label: formation CACES
  bec:
    type: boolean
    source: catalogue
    label: formation BEC
  bilan_de_competences:
    type: boolean
    source: catalogue
    label: bilan de compétences
    gender: masculine
  permis_b:
    type: boolean
    source: catalogue
    label: permis B
    gender: masculine
  qualifiante:
    type: boolean
    source: catalogue
    label: formation qualifiante
  vae:
    type: boolean
    source: catalogue
    label: formation VAE
  clea:
    type: boolean
    source: catalogue
    label: formation CléA
  rncp:
    type: boolean
    source: catalogue
    xpath: boolean(//certification/code-RNCP/child::text())
    label: formation RNCP
    description: cette formation est inscrite au RNCP
  niveau_sortie:
    description: le niveau du diplôme de sortie (licence, master…)
    type: integer
    format: int32
    label: niveau de sortie de la formation
    source: catalogue
    xpath: number(//code-niveau-sortie/child::text())
    gender: masculine
financement:
  nom:
    type: string
    public: true
    label: nom du financement
  tags:
    type: array
    items:
      type: string
    public: true
    label: catégories du financement
  eligible:
    description: définit si le financement est éligible
    type: boolean
    public: true
    label: financement éligible
  description:
    description: description du financement
    type: string
    public: true
  demarches:
    description: démarches à accomplir pour obtenir le financement
    type: string
    public: true
  remuneration:
    type: integer
    format: int32
    public: true
    nullable: true
    label: rémunération possible
  plafond_remuneration:
    type: integer
    format: int32
    public: true
    nullable: true
    label: plafond de rémunération applicable
  prise_en_charge:
    type: integer
    format: int32
    public: true
    nullable: true
    label: montant de prise en charge applicable
    description: valeur définie seulement si le prix horaire de la formation est défini
  plafond_prise_en_charge:
    type: integer
    format: int32
    public: true
    nullable: true
    label: plafond de prise en charge
    description: Ce champ est défini quand on ne connaît pas le prix horaire de la formation. C'est donc une prise en charge maximale théorique, la prise en charge réelle dépendra du prix exact de la formation.
  plafond_financier:
    type: integer
    format: int32
    label: plafond financier applicable
  plafond_horaire:
    type: integer
    format: int32
    label: plafond horaire applicable
    description: nombre maximal d'heures prises en charge
  plafond_prix_horaire:
    type: integer
    format: int32
    public: true
    label: prix horaire plafond applicable
    description: prix horaire maximum
  prix_horaire:
    type: integer
    format: int32
    label: prix horaire applicable
  reste_a_charge:
    type: number
    format: float
    public: true
    label: reste à charge applicable
  ressources:
    type: array
    public: true
    items:
      type: string
      format: url
    description: Liste d'adresses Internet pour en savoir plus sur le sujet.
  organisme:
    nom:
      public: true
      type: string
      label: nom de l'organisme
    agence:
      description: le nom de l'antenne locale à contacter le cas échéant
      type: string
      label: nom de l'agence à contacter
    adresse:
      public: true
      type: string
      label: adresse postale de l'organisme
    telephone:
      public: true
      type: string
      label: téléphone de l'organisme
    web:
      public: true
      type: string
      label: site web de l'organisme
financements: {}
