constante:
  codes_financeur_collectif:
    description: ensemble des codes financeurs collectifs
    type: List[int]
    value: [2, 4, 6, 8, 9, 11, 12, 13, 15, 16]
    label: codes financeurs collectifs
  idcc_artisanat:
    description: ensemble des codes IDCC de l'artisanat
    type: List[int]
    value: [12345]
    label: codes IDCC de l'artisanat
  codes_cpf_vae:
    description: liste des codes CPF identifiant une formation VAE
    type: List[int]
    value: [200]
    label: codes CPF VAE
  codes_cpf_clea:
    description: liste des codes CPF identifiant une formation CleA
    type: List[int]
    value: [201, 207, 208]
    label: codes CPF CleA
  deux_smic:
    type: integer
    format: int32
    value: 2997
    label: deux fois le SMIC
  trois_smic:
    type: integer
    format: int32
    value: 2997
    label: trois fois le SMIC
  domaine_formacode_langue:
    description: le domaine FORMACODE des formations en langue
    type: integer
    value: 152
    label: domaine FORMACODE langues
  codes_certifinfo_permis_b:
    type: List[int]
    value: [54664]
    label: codes CERTIFINFO pour un permis B
  codes_certifinfo_bilan_de_competences:
    type: List[int]
    value: [93559]
    label: codes CERTIFINFO pour un bilan de compétences
  codes_certifinfo_bulats:
    type: List[int]
    value: [95271, 84165, 84384]
    label: codes CERTIFINFO BULATS
  codes_certifinfo_bec:
    type: List[int]
    value: [84166, 98623]
    label: codes CERTIFINFO BEC
  codes_certifinfo_toeic:
    type: List[int]
    value: [84168]
    label: codes CERTIFINFO TOEIC
  codes_certifinfo_caces:
    type: List[int]
    value: [55673, 55674, 55675, 55676, 55677, 55803, 55804, 55805, 55806,55807, 55808, 55809,55810, 55811, 55812, 55813, 55814, 55815, 55816, 55817, 55818, 55819, 55820, 55822, 55821, 55823, 55824, 55825, 55826, 55827, 84700, 84449, 84700, 84715, 85312, 85338]
    label: codes CERTIFINFO CACES
beneficiaire:
  droit_prive:
    description: le bénéficiaire est salarié d'une entreprise de droit privé
    type: boolean
    public: true
    required: true
    label: bénéficiaire de droit privé
  solde_cpf:
    description: solde du compte CPF du bénéficiaire
    type: integer
    format: int32
    public: true
    required: true
    label: solde CPF du bénéficiaire
  remuneration:
    description: Rémunération actuelle en euros
    type: integer
    format: int32
    public: true
    required: true
    label: rémunération du bénéficiaire
  age:
    description: âge du beneficiaire
    type: integer
    format: int32
    public: true
    label: âge du bénéficiaire
  experience_professionnelle:
    description: nombre de mois travaillés sur les 5 dernières années
    type: integer
    format: int32
    public: true
    label: expérience professionnelle du bénéficiaire dans les cinq dernières années
  mois_travailles_en_cdd:
    description: nombre de mois travaillés sur un contrat CDD sur les 12 derniers mois
    type: integer
    format: int32
    public: true
    label: nombre de mois travaillés par le bénéficiaire dans la dernière année
  contrat:
    description: type de contrat du bénéficiaire
    type: string
    public: true
    required: true
    enum:
      cdd: CDD
      cdi: CDI
      intermittent: intermittent
      interim: intérimaire
    label: type de contrat du bénéficiaire
  anciennete_entreprise_actuelle:
    description: ancienneté en mois dans l'entreprise actuelle
    type: integer
    format: int32
    public: true
    label: ancienneté du bénéficiaire dans son entreprise
  entreprise:
    naf:
      description: l'identifiant NAF/APE de l'entreprise
      type: string
      public: true
      label: code NAF de l'établissement du bénéficiaire
    idcc:
      description: l'identifiant de convention collective de l'établissement
      # TODO: uniformize the type (int but 0234 so str?)
      type: integer
      format: int32
      public: true
      required: true
      label: IDCC de l'établissement du bénéficiaire
    commune:
      description: code INSEE de la commune de l'établissement du bénéficiaire
      type: string
      public: true
      # required: true  # Make me required when LBF is ready
      pattern: (2[AB]|[0-9]{2})[0-9]{3}
      label: code INSEE de la commune de l'établissement du bénéficiaire
    region:
      description: région de l'entreprise
      type: string
      label: région de l'établissement du bénéficiaire
      enum:
        '01': Guadeloupe
        '02': Martinique
        '03': Guyane
        '04': La Réunion
        '06': Mayotte
        '11': Île-de-France
        '24': Centre-Val de Loire
        '27': Bourgogne-Franche-Comté
        '28': Normandie
        '32': Nord-Pas-de-Calais-Picardie
        '44': Alsace-Champagne-Ardenne-Lorraine
        '52': Pays de la Loire
        '53': Bretagne
        '75': Aquitaine-Limousin-Poitou-Charentes
        '76': Languedoc-Roussillon-Midi-Pyrénées
        '84': Auvergne-Rhône-Alpes
        '93': Provence-Alpes-Côte d'Azur
        '94': Corse
formation:
  numero:
    description: identifiant INTERCARIF de la formation
    type: string
    public: true
    label: identifiant de la formation
  code_financeur:
    description: code financeur
    type: List[int]
    source: catalogue
    label: code financeur de la formation
  eligible_copanef:
    description: cette formation est au catalogue COPANEF
    type: boolean
    source: routine.extraire_copanef
    label: formation éligible COPANEF
  regions_coparef:
    description: régions d'éligibilité si COPAREF dans les listes_eligibilite_cpf
    type: List[int]
    source: routine.formation_region
    label: régions éligibles COPAREF
  codes_formacode:
    type: List[int]
    source: catalogue
    label: liste des codes FORMACODE de la formation
  domaines_formacode:
    description: domaines (trois premiers caractères des codes) FORMACODE de la formation
    type: List[int]
    source: catalogue
    label: liste des domaines FORMACODE de la formation
  codes_certifinfo:
    type: List[int]
    source: catalogue
    label: liste des codes CERTIFINFO de la formation
  heures:
    type: integer
    format: int32
    label: durée en heures de la formation
  mois:
    type: integer
    format: int32
    label: durée en mois de la formation
  taux_horaire:
    type: integer
    format: int32
    label: taux horaire de la formation
  taux_horaire_ttc:
    type: integer
    format: int32
    label: taux horaire TTC de la formation
  taux_horaire_ht:
    type: integer
    format: int32
    label: taux horaire HT de la formation
  cpf:
    description: code CPF de la formation (plusieurs? cf tag_cpf)
    type: integer
    format: int32
    source: catalogue
    label: code CPF de la formation
  codes_naf:
    description: codes NAF des différents CPNE
    type: List[int]
    source: routine.naf_from_formation
    label: codes NAF CPNE éligibles
  foad:
    type: boolean
    source: catalogue
    label: formation ouverte à distance
  toeic:
    type: boolean
    source: catalogue
    label: formation TOEIC
  bulats:
    type: boolean
    source: catalogue
    label: formation BULATS
  caces:
    type: boolean
    source: catalogue
    label: formation CACES
  bec:
    type: boolean
    source: catalogue
    label: formation BEC
  bilan_de_competences:
    type: boolean
    source: catalogue
    label: bilan de compétences
  permis_b:
    type: boolean
    source: catalogue
    label: permis B
  niveau_sortie:
    description: le niveau du diplôme de sortie (licence, master…)
    type: integer
    format: int32
    label: niveau de sortie de la formation
financement:
  nom:
    type: string
    public: true
    label: nom du financement
  # Do not use "type" for now, it's used as duck typing.
  genre:
    type: string
    public: true
    label: type de financement
  eligible:
    description: définit si le financement est éligible
    type: boolean
    public: true
    label: financement éligible
  description:
    description: description du financement
    type: string
    public: true
  demarches:
    description: démarches à accomplir pour obtenir le financement
    type: string
    public: true
  remuneration:
    type: integer
    format: int32
    public: true
    nullable: true
    label: rémunération possible
  prise_en_charge:
    type: integer
    format: int32
    public: true
    nullable: true
    label: montant de prise en charge possible
  plafond_financier:
    type: integer
    format: int32
    label: plafond financier applicable
  plafond_horaire:
    type: integer
    format: int32
    label: plafond horaire applicable
  taux_horaire:
    type: integer
    format: int32
    label: taux horaire applicable
  reste_a_charge:
    type: number
    format: float
    label: reste à charge applicable
  organisme:
    nom:
      public: true
      type: string
      label: nom de l'organisme
financements: {}
